#!/usr/bin/env bash

declare -r ifs_lb=$'\n'
declare -r ifs_old=${IFS:-${ifs_lb}}
export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
export IFS="${ifs_old}"

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

set -umeTE;
set +f;
set -o pipefail;





get_unix_timestamp_local() {
    bash --restricted --norc -c 'unset TZ;'
}

unset TZ;
declare -i datenow_unix_local=$(date +'%s');
declare -- display_cur='';
declare -- tmp='';
datenow() {
    datenow_unix=1769401010;
    tmp=
    if [ "" != "" ]; then
        display_cur=""
        echo -en "\r\x1b[A"
        if ((  )); then
            false && echo -en "\r\x1b[A" || true
        fi
        echo ""
    fi
    sleep 0.314
}


while true; do
    echo -en '\x1b[s'
    datenow
done
