#!/usr/bin/env bash
# shellcheck disable=SC2004,SC2206,SC2068,SC2086

set -e
set -o pipefail
export IFS=$'\n'

this_script_path="${BASH_SOURCE[0]}"
script_name="$(basename "${this_script_path}")"
script_path="$(dirname "${this_script_path}")"

declare -a argv=($@)
declare argc=${#argv[@]}

declare -a list_of_pids=()
declare -i list_of_pids_count=()

declare -A entries_by_pid=()
declare -i entries_by_pid_count=()

declare -a lsof_keys=(
    "COMMAND"
    "PID"
    "USER"
    "FD"
    "TYPE"
    "DEVICE"
    "SIZE_OFF"
    "NODE"
    "NAME"
)

error_prefix_color_rgb="$((0xFF));$((0x00));$((0x42))"
error_color_rgb="$((0xFF));$((0x32));$((0x32))"
error_color_rgb="$((0xFF));$((0x3E));$((0x5C))"
warn_prefix_color_rgb="$((0xFF));$((0x6A));$((0x32))"
warn_color_rgb="$((0xFF));$((0xA1));$((0x32))"

on_exit() {
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn() {
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${script_name} warn]\x1b[1;38;2;${warn_color_rgb}m ${@}\x1b[0m"
}
error() {
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${script_name} error]\x1b[1;38;2;${error_color_rgb}m ${@}\x1b[0m"
}

process_argv() {
    repl no echo
    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
        if 2>/dev/random 1>/dev/random ack '^[1-9]\d*$' <<<"${arg}"; then
            list_of_pids+=("${arg}")
        else
            warn "invalid PID number in command-line argument ${current}/${argc}: ${arg@Q}"
        fi
    done
    list_of_pids_count=${#list_of_pids[@]}
    if [ ${list_of_pids_count} -eq 0 ]; then
        for tmppid in $(ps aux | ack -i "(bash|ghostty|wezterm|terminal|emacs|vim)" | ack -v ack | awk '{ print $2 }'); do
            if [ "${tmppid}" != "$$" ]; then
                list_of_pids+=("${tmppid}")
            fi
        done
    fi
    list_of_pids_count=${#list_of_pids[@]}
    if [ ${list_of_pids_count} -eq 0 ]; then
        exit_error "missing argument: <PIDS...>"
        exit 1
    fi
    repl sane
}

main() {
    unset IFS
    for index in ${!list_of_pids[@]}; do
        current=$(($index + 1))
        pos="${current}/${list_of_pids_count}"

        proc_pid=${list_of_pids[$index]}
        declare -i bash_wip_proc_pid="${proc_pid}"
        declare psrow="$(ps aux | ack "^\w+\s+\b${bash_wip_proc_pid}\b\s+")"
        declare -a psname=($(echo "${psrow}" | sed -n "s/^\([^[:space:]]\+[[:space:]]\+\)\{10\}\([^[:space:]]\+.*\)/\2/gp"))
        if [ ${#psname[@]} -eq 0 ]; then
            # warn "\x1b[1;38;5;202m[${pos}] ignoring unknown pid: ${bash_wip_proc_pid}\x1b[0m"
            continue
        fi
        export IFS=$'\n'
        declare -a lsof_entries=($(lsof -p "${bash_wip_proc_pid}" | ack -v '^COMMAND\s+PID\s+USER'))

        declare -a open_files=()
        declare full_entry="${bash_wip_proc_pid@A};\n${psname[@]@A};\n${lsof_entries[@]@A};\n"

        for row in ${lsof_entries[@]}; do
            declare -A key_value_open_files=()
            for regex_group_index in ${!lsof_keys[@]}; do
                field_name="${lsof_keys[$regex_group_index]}";
                key="${field_name@L}";
                value=$(sed -n "s/^\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]\+\)\([^[:space:]]\+\)\([[:space:]]*\)\$/\${regex_group_index}/gp" <<< "${row}");
                key_value_open_files+=(["${key}"]="${value}")
            done
            open_filename_path="${key_value_open_files['name']}"
            open_filename_type="${key_value_open_files['type']}"
            open_filename_device="${key_value_open_files['device']}"
            open_filename_fd="${key_value_open_files['name']}"
            open_filename_node="${key_value_open_files['name']}"
            open_files+=("${open_filename_path@Q} # [type=${open_filename_type@Q} device=${open_filename_device@Q} fd=${open_filename_fd@Q} node=${open_filename_node@Q}]");
        done
        unset IFS

        declare sanitized_entry=""
        if runproclike_exec=$(2>/dev/random which runproclike); then
            stderr=$(mktemp)
            unset IFS
            declare -a runproclike_call=(${runproclike_exec} --omit-comments --pid "${bash_wip_proc_pid}")
            if ! runproclike_entry=$(2>${stderr} ${runproclike_call[@]}); then
                warn "\x1b[1;38;5;202m[${pos}] command failed: ${runproclike_call[@]}\x1b[0m"
                error "$(cat "${stderr}")"
                rm -f "${stderr}"
            else
                sanitized_entry="${runproclike_entry}"
                full_entry="${full_entry};\n${sanitized_entry@A};\n"
                rm -f "${stderr}"
            fi
            rm -f "${stderr}"
        fi
        echo -e "# PID ${bash_wip_proc_pid} \`${psname}\`\n"
        echo '```shell'
        echo -e "\n${full_entry}\n"
        echo '```'
    done

}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    process_argv ${argv[@]}
    main
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
