#!/usr/bin/env bash
set -umeTE; set +f; set -o pipefail; export IFS=$'\n';

declare -a cargo_cbt_all_features_wipe_docs_run=(
    --all-features --wipe --docs --run
)

declare -a cargo_cbt_wipe_docs_run=(
    --wipe --docs --run
)

declare -a call_args_varname_list=(
    "cargo_cbt_all_features_wipe_docs_run"
    "cargo_cbt_wipe_docs_run"
)

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -a stdin_lines=(${@})
declare -i stdin_line_count=${#stdin_lines[@]}
declare -- git_repo_path=""
declare -i code=0
declare -i argv_return_code=0
declare -i stdin_return_code=0

declare -- curdir="$PWD"
if [ -z "${PWD}" ]; then
    curdir=$(pwd)
fi

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty "${stty_args[@]}"
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}


main() {
    local -- varname=""
    local -- file_prefix=""
    local -- stdout=""
    local -- stderr=""
    local -- pidfile=""
    local -- timefile=""
    local -i now=$(date --utc +%s)
    local -- date_suffix=$(date --date=@${now} +'%Y-%m-%d.%H-%M-%S.%s')
    local -- call_args=()

    local -i index=0
    local -i current=0
    local -- arg=""

    local -i total_call_args_vars=${#call_args_varname_list[@]}
    local -- project=$(basename "$(pwd)")

    local -- main_log_file="${script_name}.${project}.main.log"
    for index in ${!call_args_varname_list[@]}; do
        varname="${call_args_varname_list[${index}]}"
        current=$(($index + 1))
        arg="${call_args_varname_list[$index]}"
        pos=$(printf '%*s of %s' ${#total_call_args_vars} ${current} ${total_call_args_vars})

        if [[ -v refvar ]]; then
            unset -n refvar
        fi
        local -I -n refvar="${varname}";
        call_args=( cargo cbt ${refvar[@]} )

        now=$(date --utc +%s)
        date_suffix=$(date --date=@${now} +'%Y-%m-%d.%H-%M-%S.%s')

        # file_prefix="cargo_cbt.${varname##cargo_cbt_}.${date_suffix}"
        file_prefix="cargo_cbt.${varname##cargo_cbt_}"
        stdout="${file_prefix}.stdout.log"
        stderr="${file_prefix}.stderr.log"
        pidfile="${file_prefix}.pid"
        timefile="${file_prefix}.timing"
        local -- subpid=''
        echo "[${date_suffix} ${project} build ${pos}] started" | tee -a ${stdout} | tee -a ${stderr} > ${main_log_file}
        echo "stdout: ${stdout}" > ${main_log_file}
        echo "stderr: ${stderr}" > ${main_log_file}
        echo "pidfile: ${pidfile}" > ${main_log_file}
        echo "timefile: ${timefile}" > ${main_log_file}
        echo "cargo cbt ${call_args[@]}" | tee -a ${stdout} | tee -a ${stderr} > ${main_log_file}
        1>${stdout} 2>${stderr} time -o ${timefile} cargo cbt --all-features --wipe --docs --quiet --run < /dev/null &
        subpid=${!}
        1>${pidfile} echo "${subpid}"
        fg
        now=$(date --utc +%s)
        date_suffix=$(date --date=@${now} +'%Y-%m-%d.%H-%M-%S.%s')
        echo "[${date_suffix} ${project} build ${pos}] finished" | tee -a ${stdout} | tee -a ${stderr} > ${main_log_file}
        1>${stdout} 2>${stderr} time -o ${timefile} cargo cbt --all-features --wipe --docs --quiet --run < /dev/null &
    done

}

validate_cwd() {
    local -- crate_path="$(pwd)"
    local -- manifest_path="${crate_path}/Cargo.toml"
    if [ ! -e "${manifest_path}" ]; then
        error_prefixed "[cargo build error]" "current directory does not have Cargo.toml manifest"
        exit 1
    elif [ ! -r "${manifest_path}" ]; then
        error_prefixed "[cargo build error]" "manifest not readable: ${manifest_path@Q}"
        exit 1

    elif [ ! -s "${manifest_path}" ]; then
        error_prefixed "[cargo build error]" "empty manifest file: ${manifest_path@Q}"
        exit 1
    fi
}

1>&2 echo -en "\x1b[2J\x1b[3J\x1b[H"
validate_cwd
main
