#!/bin/sh

find ${HOME} -type d -regextype egrep -regex '.*[.](DocumentRevisions-V100|TemporaryItems)' -exec rm -fr {} \; &
disown -a
find ${HOME} -name .DS_Store -type f -exec rm -fv {} \; &
disown -a
