#!/usr/local/bin/uv run --python 3.11 --with "click" --script
import sys
import click


class sint(str):
    def __init__(self, val: str):
        self.val = val.upper().replace("R", "-").replace("N", "-").replace("O", "+").replace("P", "+")

    def __sub__(self, other):
        return int(self.val) - int(other)

    def __add__(self, other):
        return int(self.val) + int(other)


def chop(container, start, end, sep):
    try:
        if end is None:
            return container[start-1]
        return sep.join(container[start-1:end-1])
    except IndexError:
        return ""


@click.command()
@click.argument('start', type=sint)
@click.argument('end', type=sint, default=None, required=False)
@click.argument('sep', default="", required=False)
def main(start, end=None, sep=""):
    if sys.stdin.isatty():
        sys.stderr.write(f"this program only works with data from STDIN for now...\n")
        raise SystemExit(0x54)

    for line in sys.stdin.readlines():
        print(chop(line.split(), start, end, sep if sep else ""))


if __name__== '__main__':
    main()
