#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

on_exit() {
    set +x
    1>/dev/null 2>/dev/null stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -a stdin_lines=()
declare -i stdin_line_count=0

declare -i code=0

declare -i current=0

declare -i index=0
declare -- arg=''
declare -- param=''

declare -i next_index=0
declare -- next_arg=''
declare -- next_param=''

declare -i skip_next=0

declare -i lineno=0
declare -i line_number=0
declare -- line=''

declare -- argument=''
declare -- field=''
declare -- key=''
declare -- name=''
declare -- path=''
declare -- value=''

declare -A unique_file_map=()
declare -a dua_input_files=()

declare -a stdin_lines=()
declare -i stdin_line_count=0

if [ ! -t 0 ]; then
    export IFS=$'\n'
    while read line; do
        if ! stdin_lines+=("${line}"); then
            continue
        fi
    done </dev/stdin
fi
stdin_line_count=${#stdin_lines[@]}

add_input_file() {
    local -- input_path="${@}"
    if [ -z "${input_path}" ]; then
        return 13
    fi
}

for index in ${!argv[@]}; do
    arg="${argv[${index}]}"
    if [ ! -e "${arg}" ]; then
        continue
    fi
    if [[ -v unique_file_map["${arg}"] ]]; then
        unique_file_map["${arg}"]="${index}"
        dua_input_files+=("${arg}")
    fi
done
for index in ${!stdin_lines[@]}; do
    line="${stdin_lines[${index}]}"
    if [ ! -e "${line}" ]; then
        1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"

    fi
    if [[ -v unique_file_map["${line}"] ]]; then
        unique_file_map["${line}"]="${index}"
        dua_input_files+=("${line}")
    fi
done

dua | ansistrip | ack '^\s+(0\s+B\b|[1-8][.]0+\s+KiB)\s+' | lastcol  | xargs -Ieach echo "rm -rfv each"
