#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

# if [ "$(id -u)" != "0" ] && [ "$(id -un)" != "root" ]; then
#     sudo -E ${this_script_path}
#     exit 0
# fi

on_exit() {
    set +x
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

list_external_volumes() {
    df -h | gawk '{
    if (NF >=6) {
        mounted_on="";

        for (i=6;i<=NF;i++) {
            mounted_on=sprintf("%s%s%s", mounted_on, $i, FS)
        }

        if (mounted_on ~ /^\/Volumes/) {
            print(mounted_on)
        }
    }
}'
}
kill_processes_hogging_volume() {
    name="${@}"
    volume="/Volumes/${name}"
    lsof | gawk "(\$0 ~ /${volumes//\/\\\//}/){
	location = \"\"
	for (i = 9; i <= NF; i++) {
		len = length(\$i)
		last = \"\"
		if (len > 0) {
			last = FS
		} else {
			last = \"\"
		}
		location = sprintf(\"%s%s%s\", location, \$i, last)
	}
	print (location)
}"
}

retry_force_eject_volume() {
    volume="${@}"
    1>&2 echo diskutil unmount force "${volume}"
    if sudo diskutil unmount force "${volume}"; then
        1>&2 echo -e "\x1b[1;38;5;106m${volume} \x1b[1;38;5;220mwas ejected forcefully\x1b[0m"
    else
        1>&2 echo -e "\x1b[1;38;5;220mfailed to eject \x1b[1;38;5;106m${volume} \x1b[1;38;5;145m(maybe in use or already ejected ?)\x1b[0m"
    fi
}
eject_volume() {
    volume="${@}"
    1>&2 echo diskutil unmount "${volume}"
    if sudo diskutil unmount "${volume}"; then
        1>&2 echo -e "\x1b[1;38;5;154m${volume} \x1b[1;38;5;220mwas ejected\x1b[0m"
    else
        retry_force_eject_volume "${volume}"
    fi
}

main() {
    for name in $(list_external_volumes); do
        eject_volume "${name}"
    done
}

# if [ "${0}" == "${script_name}" ]; then
#     main
# else
#     1>&2 echo -e "${script_name} appears to being used as a library by ${0@Q}"
# fi
main
