#!/usr/bin/env bash

program="$(basename $0)"
default_path="$HOME/projects"


admonition() {
    echo -en "\r"
    bg=${1}
    shift
    fg=${1}
    shift
    prefix="${1}"
    shift
    text="$@"
    if [ -z "${text}" ]; then
        echo -en " "
    fi
    1>&2 echo -en "\r\x1b[1;48;5;${bg}m\x1b[1;38;5;${fg}m${prefix}\x1b[0m "
    if [ -n "${text}" ]; then
        echo -en "\x1b[1;48;5;${fg}m\x1b[1;38;5;${bg}m${text}\x1b[0m"
    fi
    reset
}

cls() {
    echo -e "\x1b[2J\x1b[3J\x1b[H"
}
reset() {
    echo -e "\x1b[0m"
}
error() {
    admonition 196 16 ERROR "$@"
}
usage() {
    admonition 231 16 USAGE "$@"
}

abort() {
    error "$@"
    exit 1
}

clear_autosave_in_path() {
    path="$@"

    if [ -z "${path}" ]; then
        error "missing argument <path-to-directory>"
        usage "${program} <path-to-directory>"
        exit 1
    fi

    if [ ! -d "${path}" ]; then
        error "\"${path}\" is not a directory"
        usage "${program} <path-to-directory>"
        exit 1
    fi
    find "${path}" -type f -name "#*#" -or  -type f -name ".#*#" -exec rm -f "{}" \; &
    disown -h
}

if [ -z "$@" ]; then
    path="${default_path}"
else
    path="$@"
fi
if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    clear_autosave_in_path "${path}"
fi
