#!/usr/bin/env bash
# shellcheck disable=SC2004,SC2206,SC2068,SC2086

set -e
set -o pipefail
set -o noglob
set -u
export IFS=$'\n'

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -a argv=($@)
declare argc=${#argv[@]}

declare -- tmp_backup_path=""
declare -a garbage_file_paths=($(find . -name '*#*' -or -name '.*#*'))
declare -i garbage_file_count=${#garbage_file_paths[@]}
declare -- here=$(path canon -f .)
declare -- now=$(date +"%Y/%m/%d %H:%M:%S %Z")
if [ ${garbage_file_count} -eq 0 ]; then
    # 1>&2 echo -e "no emacs garbage files found in ${here}"
    exit 0
fi

declare -- error_prefix_color_rgb="255;0;66"
declare -- error_color_rgb="255;50;50"
declare -- error_color_rgb="255;62;92"
declare -- warn_prefix_color_rgb="255;106;50"
declare -- warn_color_rgb="255;161;50"

teardown() {
    for path in ${garbage_file_paths[@]}; do
        rm -f "${path}"
    done
    if [ -n "${tmp_backup_path}" ] && [ -e "${tmp_backup_path}" ]; then
        rm -rf "${tmp_backup_path}"
    fi
}
on_exit() {
    teardown
    repl sane
}
on_ctrlc() {
    teardown
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${prefix}]\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[${script_name} warn at ${linenum}]" "${@}"
}

error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[${script_name} error at ${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${prefix}]\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}

declare -a garbage_files_to_pack=$(
    declare -- gfp=""
    declare -- path=""
    for gfp in ${garbage_file_paths[@]}; do
        if path=$(2>/dev/random path canon "${gfp}"); then
            echo "${path}"
        else
            rm -fv "${gfp}"
        fi
    done
)

declare -- banner=$(echo -e "emacs garbage files found in ${here} at ${now}:
$(
    declare -- gfp=""
    for gfp in ${garbage_file_paths[@]}; do
        if declare -- path=$(2>/dev/random path canon "${gfp}" | xargs ls -lh); then
            echo "${path}"
        else
            rm -fv "${gfp}"
        fi
    done
)
")
if [ ${#garbage_files_to_pack[@]} -eq 0 ]; then
    exit 0
fi

declare -- now_slug=$(slugify-string "${now}")

echo -en "\x1b[2J\x1b[3J\x1b[H"
declare -- receipt_path="${tmp_backup_path}/emacs-gc.receipt.${now_slug}.txt"
declare -- tarball_path="${tmp_backup_path}/emacs-gc.${now_slug}.tgz"

echo -e "${banner}" >${receipt_path}

garbage_files_to_pack+=("${receipt_path}")

declare -- stdout=$(mktemp)
declare -- stderr=$(mktemp)

repl no echo

1>&2 echo -e "packing up emacs garbage..."

if 2>${stderr} 1>${stdout} tar czvf "${tarball_path}" ${garbage_files_to_pack[@]}; then
    1>&2 echo -e "\x1b[A\rpacking up emacs garbage... OK"
else
    set +x
    stdout=$(cat ${stdout})
    stderr=$(cat ${stderr})
    1>&2 echo -e "\x1b[A\rpacking up emacs garbage... ERROR\n"
    # error_prefixed "cleaning up temporary bin" "\n$(rm -rfv "${tmp_backup_path}")\n"

    if [ ${#stdout} -gt 0 ]; then
        warn_prefixed "stdout" "${stdout}"
    fi
    if [ ${#stderr} -gt 0 ]; then
        error_prefixed "stderr" "${stderr}"
    fi
    exit 1
fi

declare -- landfill_path="$HOME/.emacs.d/landfill"

if [ ! -e "${landfill_path}" ]; then
    mkdir -p "${landfill_path}"
elif [ ! -d "${landfill_path}" ]; then
    warn "warning" "landfill path is not a directory: ${landfill_path@Q}"
    landfill_path="$HOME/.emacs.d"
fi

if [ -d "${landfill_path}" ]; then
    1>&2 echo -e "moving garbage to landfill..."
    if 1>${stdout} 2>${stderr} mv -fv "${tarball_path}" "${landfill_path}"; then
        1>&2 echo -e "\r\x1b[Amoving garbage to landfill... OK"
    else
        stdout=$(cat ${stdout})
        stderr=$(cat ${stderr})
        1>&2 echo -e "\r\x1b[Amoving garbage to landfill... ERROR\n"
        if [ ${#stdout} -gt 0 ]; then
            warn_prefixed "stdout" "${stdout}"
        fi
        if [ ${#stderr} -gt 0 ]; then
            error_prefixed "stderr" "${stderr}"
        fi
    fi
fi

teardown
