#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -a stdin_lines=()
declare -i stdin_line_count=0

# has_params "boolean flag" - .i.e.:  "(( ${has_params} ))"
#
# "false' if the sum of ${argc} + ${stdin_line_count} is 0
# otherwise, otherwise 1 (or any positive integer: true)
declare -i has_params=$((argc))
has_params=$((argc + stdin_line_count))

declare -i code=0

declare -i current=0

declare -i index=0
declare -- arg=''
declare -- param=''

declare -i next_index=0
declare -- next_arg=''
declare -- next_param=''

declare -i skip_next=0

declare -i lineno=0
declare -i line_number=0
declare -- line=''

declare -- argument=''
declare -- field=''
declare -- key=''
declare -- name=''
declare -- path=''
declare -- value=''

declare -- stderr="$(mktemp)"

# <STDIN>
declare -a stdin_lines=()
declare -i stdin_line_count=0

if [ ! -t 0 ]; then
    export IFS=$'\n'
    while read line; do
        if ! stdin_lines+=("${line}"); then
            continue
        fi
    done </dev/stdin
fi
stdin_line_count=${#stdin_lines[@]}
has_params=$((argc + stdin_line_count))
# </STDIN>

export IFS=$'\n'

declare -a inputs=("${@}")
declare -- input=''
declare -- output="${input}"
declare -a regexp_list=(
    '[\\]{2}([|])'
    '[\\]{1}([|])'
    '[^(|)]'
)
declare -i index=0
declare -i current=0
declare -- regexp=''
declare -- value=''
declare -- hex_encoded=''
declare -- b64_encoded=''
declare -a transforms=()
declare -A transforms_map=()
declare -i total=${#regexp_list[@]}

export IFS=$'\n'
if (($argc)); then
    for index in ${!argv[@]}; do
        current=$((${index} + 1))
        arg="${argv[${index}]}"
        inputs+=("${arg}")
    done
    unset IFS
    inputs+=("${argv[@]}")
fi

if (($stdin_line_count)); then
    export IFS=$'\n'
    inputs+=($(echo "${stdin_lines[*]}"))
fi

if ! ((${has_params})); then
    1>&2 echo "[${script_name} error] missing command-line arguments (or stdin data)"
    exit 1
fi

for input in ${inputs[@]}; do
    for index in ${!regexp_list[@]}; do
        current=$((index + 1))
        regexp="${regexp_list[${index}]}"
        b64_encoded=$(base64 <<<"${regexp}")
        hex_encoded=$(xxd -c 1 -p <<<"${regexp}" | sed -E 's/[[:space:]\n]+//g')
        value=$(sed -E "s/${regexp}//g" <<<"${output}")

        if [[ ! -v transforms_map["${value}"] ]]; then
            transforms_map["${value}"]="${regexp}"
            transforms+=("${value}")
        fi

        if [ "${value}" != "${output}" ]; then
            if [[ ! -v transforms_map["${output}"] ]]; then
                transforms_map["${output}"]="${regexp}"
                transforms+=("${output}")
            fi
            output="${value}"
        fi

        echo "<regexp pos={${current}} of={${total}}>"
        echo "    <pattern>"
        echo "    ${regexp}"
        echo "    </pattern>"
        echo "    <quoted>"
        echo "    ${regexp@Q}"
        echo "    </quoted>"
        echo "    <base64>"
        echo "    ${b64_encoded}"
        echo "    </base64>"
        echo "    <hex>"
        echo "    ${hex_encoded}"
        echo "    </hex>"
        echo "</regexp> <!-- pos={${current}} of={${total}} -->"
        echo
    done
done
echo "${output}"
