#!/usr/bin/env bash
# .FFFFF .FFFFF 7"""""`'"""`77 PP"""""""`PP 77""""""""`7 GG'"""""`GG
# FF   " FF   " M  MM.  MM.  M PP  PPPPP  P EE  EEEEEEEE G' .GGG. `G
# FFFFF  FFFFF  M  MMM  MMM  M P'        .P E`      EEEE G  GGGGGGGG
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE  EEEEEEEE G  GGG   `G
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE  EEEEEEEE G. `GGG' .G
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE        .E GG.     .GG
#               77777777777777 PPPPPPPPPPPP 777777777777 GGGGGGGGGGG
set -e
source ffmpeg-a $1 h264.mp4
ffmpeg "$input" -c:v h264_videotoolbox -q:v 83 -c:a copy -y "$output"
