#!/usr/bin/env bash
# .FFFFF .FFFFF 7"""""`'"""`77 PP"""""""`PP 77""""""""`7 GG'"""""`GG
# FF   " FF   " M  MM.  MM.  M PP  PPPPP  P EE  EEEEEEEE G' .GGG. `G
# FFFFF  FFFFF  M  MMM  MMM  M P'        .P E`      EEEE G  GGGGGGGG
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE  EEEEEEEE G  GGG   `G
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE  EEEEEEEE G. `GGG' .G
# FF     FF     M  MMM  MMM  M PP  PPPPPPPP EE        .E GG.     .GG
#               77777777777777 PPPPPPPPPPPP 777777777777 GGGGGGGGGGG
set -e
source ffmpeg-a "$1" mov

ffmpeg \
    -i "$input" \
	-vf setfield=tff \
	-flags +ilme+ildct \
	-c:v prores \
	-profile:v 3 \
	-vendor apl0 \
	-bits_per_mb 8000 \
	-quant_mat hq \
	-mbs_per_slice 8 \
	-pixel_format yuv422p10lep \
	-vendor apl0 \
	-bits_per_mb 8000 \
	-color_range tv \
	-color_primaries bt709 \
	-color_trc bt709 \
	-colorspace bt709 \
	-vf setdar=4/3,setfield=tff \
	-y "$output"


# ffmpeg "$input" \
# 	-c:v prores_videotoolbox \
# 	-alpha_bits 0 \
# 	-bits_per_mb 8000 \
# 	-color_primaries smpte170m \
# 	-color_range 1 \
# 	-color_trc smpte2084 \
# 	-colorspace ictcp \
# 	-mbs_per_slice 8 \
# 	-profile:v 3 -pixel_format yuv422p10lep \
# 	-quant_mat hq \
# 	-vendor apl0 \
#         -y "$output"
