#!/usr/bin/env bash

export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
unset IFS

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"


declare -- default_figlet_installation_path="/usr/share/figlet"
declare -- figlet_installation_path="${default_figlet_installation_path}"
declare -- figlet_fonts_path=""
declare -- default_figlet_fonts_path=""

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -- git_repo_path=""
declare -i exit_code=0
declare -- curdir=$(pwd)
declare -a font_files=()
declare -a font_directories=()
declare -- TEXT="Hello World"


declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}

process_argv() {
    if ! default_figlet_fonts_path=$(figlet -I2); then
        exit_code=$?
        error_prefixed "[system error]" "command \x60figlet -I2\x60 failed with exit code ${exit_code} therefore could not determine figlet's default directory. Perhaps figlet is not installed?!?"
        exit ${exit_code}
    fi

    if [ ! -d "${figlet_installation_path}" ]; then
        if ! figlet_installation_path=$(brew --prefix figlet); then
            exit_code=$?
            error_prefixed "[system error]" "figlet is not installed in the default path ${default_figlet_installation_path@Q} and command \x60brew --prefix figlet\x60 failed with exit code ${exit_code}"
            exit ${exit_code}
        fi
    fi

    repl no echo
    local -i current=0
    local -i index=0
    local -- arg=""
    local -i skip_next=0
    local -- next_arg=""
    for index in ${!argv[@]}; do
        if (( $skip_next )); then
            skip_next=0
            continue
        fi
        next_arg=""
        current=$(($index + 1))
        arg="${argv[$index]}"
        if [[ -v argv[$current] ]]; then
            next_arg="${argv[$current]}"
        fi
        case "${arg}" in
            *.flf|*.flf2|*.ylf|*.tlf2)
                font_files+=("${arg}")
                ;;
            -f)
                if [ -n "${next_arg}" ]; then
                    font_files+=("${next_arg}")
                    skip_next=1
                else
                    error_prefixed "[argument error]" "missing filename argument following argument ${current} of ${argc}: ${arg@Q}"
                    exit 1
                fi
                ;;
            -f=*)
                next_arg="${arg#-f=}"
                if [ -n "${next_arg}" ]; then
                    font_files+=("${next_arg}")
                else
                    error_prefixed "[argument error]" "missing filename argument after \042=\042 ${current} of ${argc}: ${arg@Q}"
                    exit 1
                fi
            -d)
                if [ -n "${next_arg}" ]; then
                    font_directories+=("${next_arg}")
                    skip_next=1
                else
                    error_prefixed "[argument error]" "missing filename argument following argument ${current} of ${argc}: ${arg@Q}"
                    exit 1
                fi
                ;;
            -d=*)
                next_arg="${arg#-d=}"
                if [ -n "${next_arg}" ]; then
                    font_directories+=("${next_arg}")
                else
                    error_prefixed "[argument error]" "missing filename argument after \042=\042 ${current} of ${argc}: ${arg@Q}"
                    exit 1
                fi

                ;;

    done
    repl sane
}

main() {
    info_prefixed "[${script_name}]" "main"
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_argv ${argv[@]}; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
#!/bin/bash

function display() {
    local -r lpath="$(brew --prefix figlet)/share/figlet/fonts"
    for font in $(find "$lpath" -name "*.flf" -not -path '*C64*'); do
        directory=$(dirname $font)
        group_name=$(basename $directory)
        filename=$(basename $font)
        relative_path=${font##$lpath/}

        name="${filename%.*}"
        cmd="figlet -w 160 -f ${font} ${TEXT}"
        printf "\x1b[1;38;5;51m\"${TEXT}\" \x1b[0mwith font \x1b[1;38;5;220m${name} (${group_name}) \x1b[1;38;5;250m${relative_path} \x1b[1;38;5;237m${font}\x1b[0m\n\n\n"
        $cmd
        printf "\n\n"
        if [ "$?" != "0" ]; then
            exit 1
        fi
    done
}

display | bat --style grid
reset
