#!/usr/bin/env bash

path="${@:-$(pwd)}"

if [ ! -d "$path" ]; then
    g o -e2 "$path is not a directory"
    exit 1
fi
find "$path" -name node_modules -type d -not -path '*/node_modules*node_modules'
