#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"
declare -- stderr="$(mktemp)"

on_exit() {
    set +x
    bash -c "exec 1>&2;
set -umeTE; set +f; set -o pipefail;
rm -f ${stderr@Q} &
disown -a
"
}

on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -i code=0

declare -i current=0
declare -- arg=""
declare -- pos=""

declare -i index=0
declare -- arg=""
declare -- param=""

declare -i next_index=0
declare -- next_arg=""
declare -- next_param=""

declare -i skip_next=0

declare -i lineno=0
declare -i line_number=0
declare -- line=""

declare -- argument=""
declare -- field=""
declare -- key=""
declare -- name=""
declare -- path=""
declare -- value=""

# <GIT>
declare -- git_repo_path=""
declare -i under_git_repo=0
if git_repo_path=$(2>${stderr} git rev-parse --show-toplevel); then
    code=0
    under_git_repo=1
else
    code=$?
fi
if [ ${code} -ne 0 ]; then
    under_git_repo=0;
    1>&2 echo -e "\x1b[0m\x1b[1;48;2;253;67;83m[${script_name} warning]\x1b[7m $(pwd) is not under git version control\x1b[0m"
fi
# </GIT>
export IFS=$'\n'

declare -a initial_rust_artifact_paths=()
declare -a rust_artifact_paths=()
declare -a node_artifact_paths=()

declare -a spacey_locations=()

spacey_locations=(
    $(path canon '~/projects/')
    $(path canon '~/workbench/')
    $(path canon '~/Blender/')
    $(path canon '~/godot/')
    $(path canon '~/go/')
)


1>&2 echo -e "\x1b[0m\x1b[1;48;2;253;67;83m[${script_name} info]\x1b[7m searching node_modules\x1b[0m"

initial_rust_artifact_paths+=(
    $(find ${spacey_locations[@]} -regextype egrep -type d -regex '.*/Cargo.toml' -exec bash -c 'declare -- manifest="{}"; path canon "$(path parent "${manifest}" \;)/target"' \; )
)
for path in ${initial_rust_artifact_paths[@]}; do
    if [ -e "${path}" ]; then
        rust_artifact_paths+=("${path}")
    fi
done
node_artifact_paths+=( $(find ${spacey_locations[@]} -regextype egrep -type d -regex '.*/node_modules' -not -regex '.*/node_modules/.*/node_modules') )

1>&2 echo -e "\x1b[0m\x1b[1;48;2;253;67;83m[${script_name} info]\x1b[7m searching rust target\x1b[0m"


export IFS=$'\n'

echo -e "\n\n" >> node_artifacts_found.log
echo -e "\n\n" >> rust_artifacts_found.log

echo "${node_artifact_paths[*]}" >> node_artifacts_found.log
echo "${rust_artifact_paths[*]}" >> rust_artifacts_found.log
