#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"
declare -- stderr="$(mktemp)"

on_exit() {
    set +x
    bash -c "exec 1>&2;
set -umeTE; set +f; set -o pipefail;
rm -f ${stderr@Q} &
disown -a
"
}

on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -a starting_points=()
declare -A starting_points_map=()

declare -a find_args=()
declare -A find_args_map=()

declare -A unique_extensions=()

declare -g arg="" argument="" field="" key="" line="" name="" filename="" filename_extension="" filename_base="" param="" path="" pos="" value="" ext=""
declare -ig code=0 current=0 index=0 line_number=0 lineno=0 skip=0
declare -gl regex_inner="" regex=""

declare -ig allow_ts=0
declare -ig print_regex=0

export IFS=$'\n'

add_starting_point() {
    local -a argv=($@)
    local -i argc=${#argv[@]}
    local -- value=""

    if [ ${argc} -eq 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]" "missing argument: <STARTING_POINT>"
        return 1
    fi
    value="${argv[@]}"

    if [ -d "${value}" ]; then
        if [[ ! -v starting_points_map["${value}"] ]]; then
            starting_points_map["${value}"]=${#starting_points_map[@]}
            starting_points+=("${value}")
            return 0
        fi
        return 0
    else
        case "${value}" in
            --ts)
                allow_ts=1
                ;;
            --debug | --dbg | --print-regex | --regex | --print)
                print_regex=1
                ;;
            --no-ts)
                allow_ts=0
                ;;
            *)
                add_find_arg "${value}"
                ;;
        esac
        return 0
    fi
}
add_find_arg() {
    local -a argv=($@)
    local -i argc=${#argv[@]}
    local -- arg=""

    if [ ${argc} -eq 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]" "missing argument: <STARTING_POINT>"
        return 1
    fi
    arg="${argv[@]}"

    if [[ ! -v find_args_map["${arg}"] ]]; then
        find_args_map["${arg}"]=${#find_args_map[@]}
        find_args+=("${arg}")
        return 0
    fi
}
initialize_regex() {
    local -- ext=""
    for ext in $(base64 -d <<<'H4sIAAAAAAACA1XPQQ7CIBQE0P0ch3INV3qBVssPqRQKSvX2zpiYxsV/mfD/YsBgDhisACd3OVOhGVMnLZAegVu9AsGPYhJF8CTc/7AYaHJCN8n3H4tYjWSl4oQX8xc7PNDliyXWxpTNBNP2AGrSdLapeQOaavbIZc982+eJ+12/eD8JPgRjdPvrAAAA' | gunzip); do
        if ! ((${allow_ts})) && [ "${ext@L}" == "ts" ]; then
            continue
        fi
        if [[ ! -v unique_extensions["${ext@L}"] ]]; then
            unique_extensions["${ext@L}"]="${ext@L}"
        fi
    done
    export IFS=$'\x7c'
    regex_inner=$(echo "${unique_extensions[*]}" | sort -r)
    regex="(${regex_inner})"
    export IFS=$'\n'
}


for index in ${!argv[@]}; do
    current=$(($index + 1))
    arg="${argv[$index]}"
    pos="$(printf '%*s of %s' ${#argc} ${current} ${argc})"

    if add_starting_point "${arg}"; then
        code=0
    else
        code=$?
    fi
done

if [ ${#starting_points[@]} -eq 0 ]; then
    add_starting_point "$(pwd)"
fi

initialize_regex

declare -g find_regex=".*[.]${regex}\$"
declare -ga find_command_args=(
    'find' ${starting_points[@]} '-regextype' 'egrep' '-regex'
)

if ((${print_regex})); then
    echo "${find_regex@Q}"
else
    1>&2 echo "${find_command_args[@]} ${find_regex[@]@Q} ${find_args[@]}"

    for path in $(${find_command_args[@]} "${find_regex} ${find_args[@]}"); do
        echo "${path}"
    done
fi
