#!/usr/bin/env bash

export IFS=$'\n'
set -ueTE
set +f
set -o pipefail
unset IFS

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -- git_repo_path=""
declare -i exit_code=0
declare -- initial_dir=$(pwd)
declare -a find_at_paths=()
declare -A git_repo_subdirs=()

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}

process_argv() {
    export IFS=$'\n'
    repl no echo
    local -a git_status_lines=()
    local -- stderr=$(mktemp)
    local -i total_changes=0
    if ! git_repo_path=$(git rev-parse --show-toplevel); then
        error_prefixed "[${script_name} error]" "${initial_dir@Q} is not a git repo"
        exit 1
    fi

    2>/dev/random 1>/dev/random pushd "${git_repo_path}"
    if ! 2>${stderr} git_status_lines=( $(git status --porcelain | sed -E '/^[?]{2}/d') ); then
        error_prefixed "[git status error]" "$(cat "${stderr}")"
        exit 1
    fi
    total_changes=${#git_status_lines[@]}
    2>/dev/random 1>/dev/random popd

    # if [ "${initial_dir}" == "${git_repo_path}" ]; then
    #     info_prefixed "git_repo_path is current dir" "${git_repo_path}"
    # else
    #     debug_prefixed "git_repo_path is above current dir" "${git_repo_path}"
    # fi
    # exit

    if [ ${total_changes} -gt 0 ]; then
        error_prefixed "[git status error]" "git tree is dirty"
        warn_prefixed "[git status error]" "commit or stash ${total_changes} changes before calling ${script_name}"
        exit 1
    fi
    local -- resolved_path=""
    local -i current=0
    local -i index=0
    local -- arg=""

    if [ ${argc} -eq 0 ]; then
        find_at_paths=( "${initial_dir}" )
    else
        for index in ${!argv[@]}; do
            resolved_path=""
            current=$(($index + 1))
            arg="${argv[$index]}"
            if [ -e "${arg}" ]; then
                resolved_path=$(path canon "${arg}")
            else
                warn_prefixed "[argument is not an existing path]" "${arg}"
                continue
            fi

            if [ -d "${resolved_path}" ]; then
                find_at_paths=( "${resolved_path}" )
            else
                error_prefixed "[invalid path error]" "${resolved_path@Q} is a $(gstat -c %F "${resolved_path}")"
                continue
            fi
        done
    fi
    local -- lookup_dir=""
    local -- path=""
    for lookup_dir in ${find_at_paths[@]}; do
        for path in $(find ${lookup_dir} -type d -name '.git' -exec dirname {} \;); do
            git_repo_subdirs+=(["${path}"]="${lookup_dir}")
        done
    done

    repl sane
}

main() {
    local -- path=""
    for path in ${!git_repo_subdirs[@]}; do
        parent="${git_repo_subdirs[$path]}"
        path_git_subdir="${path}/.git"
        if [ ! -e "${path_git_subdir}" ]; then
            error_prefixed "[filesystem error]" "git subdir does not exist: ${path_git_subdir@Q}"
            continue
        fi
        name=$(basename ${path})
        path_git_folded="${path}/dot-git-folded-${name}"
        info_prefixed "${name}" "${path_git_folded}"
        # info_prefixed "[main]" "${path}"
    done
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_argv ${argv[@]}; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
