#!/usr/bin/env bash

set -e
set -o pipefail
# set -e
# set -o pipefail
# set -o noglob
set -u
export IFS=$'\n'

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -- include_remotes=""

error_prefix_color_rgb="$((0xFF));$((0x00));$((0x42))"
error_color_rgb="$((0xFF));$((0x32));$((0x32))"
error_color_rgb="$((0xFF));$((0x3E));$((0x5C))"
warn_prefix_color_rgb="$((0xFF));$((0x6A));$((0x32))"
warn_color_rgb="$((0xFF));$((0xA1));$((0x32))"

on_exit() {
    1>&2 echo -en '\x1b[0m';
    echo -en '\x1b[0m';
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 101
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
exit_error() {
    error "${@}"
    exit 101
}
warn() {
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${script_name} warn]\x1b[1;38;2;${warn_color_rgb}m ${@}\x1b[0m"
}
error() {
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${script_name} error]\x1b[1;38;2;${error_color_rgb}m ${@}\x1b[0m"
}

process_argv() {
    repl no echo
    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
        case "${arg}" in
            "help" | "-h" | "--help")
                usage
                exit 0
                ;;
            -a|--all)
                include_remotes="true"
                continue
                ;;
            *) ;;
        esac
    done
    repl sane
}

usage() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;5;231m$(basename $0) \x1b[1;38;5;231m[\x1b[1;38;5;202m--help\x1b[1;38;5;231m, \x1b[1;38;5;202m-h\x1b[1;38;5;231m, \x1b[1;38;5;202mhelp\x1b[1;38;5;231m, \x1b[1;38;5;247m...options\x1b[1;38;5;231m]
\x1b[0m

1. when called without arguments/options, list branches via \x1b[1;38;5;154m$(which git-list-branches)\x1b[0m
2. when called at least one argument/option in any order which matches any of \x1b[1;38;5;202m'-h'\x1b[0m, \x1b[1;38;5;202m'--help'\x1b[0m or \x1b[1;38;5;202m'help'\x1b[0m displays this help\x1b[0m.
3. when called at least one argument/option in any order which matches any of \x1b[1;38;5;202m'-a'\x1b[0m, \x1b[1;38;5;202m'--all'\x1b[0m or \x1b[1;38;5;202m'all'\x1b[0m displays both local and remote branches\x1b[0m.
4. when called with arguments/options except the above, calls \x1b[1;38;5;231mgit branch \x1b[1;38;5;202m...ARGUMENTS\x1b[0m

For example, calling:

\x1b[1;38;5;231mgit \x1b[1;38;5;154mbr\x1b[1;38;5;231m -D dummy\x1b[0m

is equivalent to calling:

\x1b[1;38;5;231mgit \x1b[1;38;5;154mbranch\x1b[1;38;5;231m -D dummy\x1b[0m

"
    repl sane
}

main() {
    local -a list_branches_argv=()
    if [ -n "${include_remotes}" ] && [ "${include_remotes@L}" == "true" ]; then
        list_branches_argv+=( "--all" )
    fi

    if [ ${argc} -eq 0 ] || [ ${#list_branches_argv[@]} -gt 0 ]; then
        git-list-branches ${list_branches_argv[@]}
    else
        git branch ${argv[@]}
    fi
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    process_argv ${argv[@]}
    main
else
    exit_error "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
