#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"
declare -- stderr="$(mktemp)"

declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -- arg=""
declare -- argument=""
declare -- field=""
declare -- key=""
declare -- line=""
declare -- name=""
declare -- filename=""
declare -- filename_extension=""
declare -- filename_base=""
declare -- param=""
declare -- path=""
declare -- pos=""
declare -- value=""
declare -i code=0
declare -i current=0
declare -i index=0
declare -i line_number=0
declare -i lineno=0
declare -i skip=0
declare -gA path_map=()
declare -i autocommit=1
declare -- working_dir="$(pwd)"

export PS4=''

export IFS=$'\n'
name=$(slugify-string "$(path name .)")

declare -- ignore_filename=".gitignore"
declare -- gitignore_path="$(path canon "${ignore_filename}")"


cd "${working_dir}"
git init
git branch -M ${name}
git config set advice.addIgnoredFile false


if [ ! -e ${gitignore_path} ] || [ ! -s "${gitignore_path}" ]; then
    1>${gitignore_path} echo -e $'/*\n*.*\n**/*\n\n!'"${ignore_filename}\n"
    git add -f ${gitignore_path}
else
    1>>${gitignore_path} echo -e $'\n\n/*\n*.*\n**/*\n\n\n!'"${ignore_filename}\n\n"
    # autocommit=0
fi

if ((${autocommit})); then
    (cd "${working_dir}" && git add -f "${ignore_filename}")
    (cd "${working_dir}" && git commit -m "initialized git repo for ${name}")
fi
