#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

on_exit() {
    set +x
    1>/dev/null 2>/dev/null stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -a stdin_lines=()
declare -i stdin_line_count=0

# has_params "boolean flag" - .i.e.:  "(( ${has_params} ))"
#
# "false' if the sum of ${argc} + ${stdin_line_count} is 0
# otherwise, otherwise 1 (or any positive integer: true)
declare -i has_params=$((argc))
has_params=$((argc + stdin_line_count))

declare -i current=0
declare -i index=0
declare -- arg=''
declare -- argument=''
declare -- field=''
declare -- filename=''
declare -- key=''
declare -- name=''
declare -- param=''
declare -- path=''
declare -- value=''
declare -- item=''

declare -i ts_created=0
declare -i ts_modified=0
declare -i code=0

declare -- stderr="$(mktemp)"

declare -- git_repo_path=""
if ! git_repo_path=$(2>${stderr} git rev-parse --show-toplevel); then
    code=$?
fi

declare -a files_to_git_add=(
    $(git status --porcelain  | grep -E '[.]log$' | lastcol)
)

for item in ${files_to_git_add[@]}; do
    path="${git_repo_path}/${item}"
    name="$(basename "${path}")"
    ts_created=$(gstat -c '%W' "${item}")
    ts_modified=$(gstat -c '%Y' "${item}")
    export GIT_AUTHOR_DATE="$(date --date=@${ts_created} +'%s %z')"
    export GIT_COMMITTER_DATE="$(date --date=@${ts_modified} +'%s %z')"
    git add "${item}" && git commit "${item}" -m "[log] ${name}"
done
