#!/usr/bin/env bash
# shellcheck disable=SC2004,SC2206,SC2068,SC2086

set -e
set -o pipefail
export IFS=$'\n'

this_script_path="${BASH_SOURCE[0]}"
script_name="$(basename "${this_script_path}")"
script_path="$(dirname "${this_script_path}")"

declare -a argv=($@)
declare argc=${#argv[@]}
declare remote_reference_name=""
declare remote_reference_hash=""

error_prefix_color_rgb="$((0xFF));$((0x00));$((0x42))"
error_color_rgb="$((0xFF));$((0x32));$((0x32))"
error_color_rgb="$((0xFF));$((0x3E));$((0x5C))"
warn_prefix_color_rgb="$((0xFF));$((0x6A));$((0x32))"
warn_color_rgb="$((0xFF));$((0xA1));$((0x32))"

on_exit() {
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <REMOTE-REFERENCE>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn() {
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${script_name} warn]\x1b[1;38;2;${warn_color_rgb}m ${@}\x1b[0m"
}
error() {
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${script_name} error]\x1b[1;38;2;${error_color_rgb}m ${@}\x1b[0m"
}

if [ ${argc} -eq 0 ]; then
    error "missing argument: <REMOTE-REFERENCE>"
    usage
    exit 1
fi

for index in ${!argv[@]}; do
    declare -i current=$(( $index + 1 ))
    arg="${argv[$index]}"
    pos="${current}/${argc}"
    if ! tmp_ref=$(2>/dev/random git rev-parse "${arg}"); then
        warn "skipping argument ${pos}, invalid git reference: ${arg@Q}"
        continue
    elif [ -z "${remote_reference_name}" ] && [ -z "${remote_reference_hash}" ]; then
        remote_reference_name="${arg}"
        remote_reference_hash="${tmp_ref}"
        continue
    else
        warn "invalid extra argument {pos} ${arg@Q}: remote git reference already defined to ${remote_reference_name} => ${remote_reference_hash}"
        continue
    fi
done

git fetch -a

1>&2 echo -e "looking for differences from remote reference ${remote_reference_name} ${remote_reference_hash}"
for path in $(git diff --raw "${remote_reference_name}" | ack '^(\S+\s+){4}D' | awk '{ print $NF }'); do
    git checkout "${remote_reference_name}" "${path}"
done
