#!/usr/bin/env bash

set -e
set -o pipefail
export IFS=$'\n'

declare -a argv=($@)
declare -i argc=${#argv[@]}

ps aux | ack -i '(agent|audio|weather|news)' | awk '{ print $2 }' | sudo xargs-each renice +12
ps aux | ack -i '(emacs|ghostty|wezterm|dock|finder)' | awk '{ print $2 }' | sudo xargs-each renice -20
