#!/usr/bin/env bash

export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
unset IFS

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"
declare -i stop_loop=0

ordinal() {
    unset IFS
    local -a ord_argv=($@)
    local -i ord_argc=${!ord_argv[@]}
    local -i index=0
    local -i current=0
    local -- arg=""
    local -a numbers=()
    local -- ord=""

    if [ ${ord_argc} -eq 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]}:${LINENO[0]}]" "missing arguments"
        exit 1
    fi

    for index in ${!ord_argv[@]}; do
        current=$(($index + 1))
        arg="${ord_argv[$index]}"
        #arg="$(sed -E 's/(^\s*|\s*$)' <<< "${ord_argv[$index]}")"
        if 1>/dev/random 2>/dev/random grep -E '^\s*[0-9]+\s*$' <<<"${arg}"; then
            numbers+=("${arg}")
        fi
    done

    for no in ${numbers[@]}; do
        ord=$(ord_num $no)
        printf '%d%s\n' "${no}" "${ord}"
    done
}

ord_num() {
    local -i number=$(($1))
    local -i abs=${number#-}
    local -i last_two=$((${abs} % 100))
    local -i last_digit=$((${abs} % 10))
    case "${last_two}" in
        11 | 12 | 13)
            echo "th"
            return
            ;;
    esac
    case "${last_digit}" in
        1)
            echo "st"
            return
            ;;
        2)
            echo "nd"
            return
            ;;
        3)
            echo "rd"
            return
            ;;
        *)
            echo "th"
            return
            ;;
    esac
}


declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -- git_repo_path=""
declare -i exit_code=0
declare -- curdir=$(pwd)

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    stop_loop=1
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    stop_loop=1
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}

process_argv() {
    if ! git_repo_path=$(git rev-parse --show-toplevel); then
        error_prefixed "[${script_name} error]" "${curdir@Q} is not a git repo"
        exit 1
    fi

    repl no echo
    local -i current=0
    local -i index=0
    local -- arg=""

    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
    done
    repl sane
}


main() {
    local -i minutes=60
    local -i count=0
    local -A instances=()
    local -a occurrences=()
    local -i now=0
    local -i started_at=$(date +%s)
    wat="Mega$(rot13 <<< 'Fran')"
    body_tmpl="PyTorch %s"
    title_tmpl="ML/Tensor Project%s"
    until (( $stop_loop )); do
        now=$(date +%s)
        count=$(( $count + 1 ))
        # echo "${count}"
        nth="${count}$(ord_num "${count}")"
        title="$(printf "${title_tmpl}" "${nth} reminder")"
        body="$(printf "${body_tmpl}" "${nth} reminder to build ${wat} predictor")"
        open -b com.apple.Preview /Users/gabrielfalcao/workbench/2025-12-17/megasena.png
        # osascript -e 'tell application "Preview" to activate' -e 'open (POSIX file "/Users/gabrielfalcao/workbench/2025-12-17/megasena.png" as alias)'
        warn_prefixed "${title}" "${body}"
        occurrences+=("${now}")
        instances+=(["${now}"]=$(echo -en "# ${title}\n\n${body}"))
        sleep $(( 7 * $minutes ))
    done
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_argv ${argv[@]}; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
