#!/usr/bin/env bash

set -e
declare -a argv=($@)
declare -i argc=${#argv}
declare -i index=0
declare -i current=0
declare -a action_args=()
declare -a known_opts=(
    "-a"
    "add"
    "-l"
    "list"
    "-p"
    "path"
    "-v"
    "verbose"
    "-x"
    "extract"
    "-h"
    "--help"
)
usage() {
    1>&2 echo "USAGE: $(basename $0) $(echo -ne "${known_opts[@]}" | sed "s/\([-]\{1,\}[a-zA-Z0-9_]\+\)/[\1]/g")"
}

action="add"
verbose="false"
path=$HOME/$(rmao -l *ocknech*/unen)/mu
mkdir -p "${path}"
declare -i slurp_args=0
if [ ${#argv} -gt 0 ]; then
    for index in ${!argv[@]}; do
        arg=${argv[${index}]}
        if (( ${slurp_args} )); then
            action_args+=("${arg}")
            continue
        fi
        case "${arg}" in
            "--help" | "-h")
                usage
                exit 0
                ;;
            "-p"|"path")
                action="show_path"
                ;;
            "-v"|"verbose")
                verbose="true"
                ;;
            "-a"|"add")
                action="add"
                ;;
            "-x"|"extract")
                action="extract"
                slurp_args=1
                ;;
            "-l"|"list")
                action="list"
                ;;
            *)
                1>&2 echo "unknown option: ${arg@Q}"
                1>&2 usage
                exit 1
                ;;
        esac
    done
fi
musgz_show_path() {
    echo "$path"
}

musgz_add() {
    cd "$path"
    target_path=$(t16g).json.enc.gz
    pbpaste | gzip > ${target_path}
    if [ "${verbose}" == "true" ]; then
        echo "${target_path}"
    fi
}
musgz_list() {
    cd "$path"
    ls -ltrh | lastcol
}

musgz_extract() {
    zcat ${action_args[@]} | mu | jaq '.[].tabs[] | select(.url | test("xvideos[.]com")) | . * {accessedSecs: .lastAccessed  / 1000}' | jaq -s | jaq '.[] | {url,accessed: {date: .accessedSecs | strftime("%Y-%m-%d"), time: .accessedSecs | strftime("%H:%M:%S"), unix: {seconds: .accessedSecs| ceil, milliseconds: .lastAccessed| ceil}}}' | jaq -s # | jaq 'sort_by(.accessed.unix.milliseconds)'
}

case "${action}" in
    "show_path")
        musgz_show_path
        ;;
    "add")
        musgz_add
        ;;
    "extract")
        musgz_extract
        ;;
    "list")
        musgz_list
        ;;
    *)
        bar_text_left 231 196 "invalid action: ${action@Q}"
        1>&2 usage
        exit 1
        ;;
esac
