#!/usr/bin/env bash
function fail(){
    echo "$@"
    exit 42
}

in_file="$@"
if [ -z "${in_file}" ]; then
    fail 'missing "in_file"'
fi

shift

out_file="${in_file/.aes-256-cbc/}"
if [ -z "${out_file}" ]; then
    fail 'missing "out_file"'
fi

set -xe


openssl aes-256-cbc -d -a -in ${in_file} -out ${out_file}
