#!/usr/bin/env bash

keyid="${1}"
shift
set -eu
declare -a KEYSERVERS=(
    pgp.mit.edu
    keyring.debian.org
    keyserver.ubuntu.com
);
echo "# Publishing key: ${keyid}"
for server in ${KEYSERVERS[*]}; do
    if gpg --keyserver "${server}" --send-keys "${keyid}"; then
        echo -e "\x1b[1;38;5;154mgpg --keyserver \x1b[1;38;5;208m${server} \x1b[1;38;5;154m--send-keys \x1b[1;38;5;220m${keyid}\x1b[0m"
    fi
done
g o
