#!/usr/bin/env bash

set -e
set -o pipefail
set -u


script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -a argv=($@)
declare argc=${#argv[@]}

declare -- ppv_url=""

error_prefix_color_rgb="255;0;66"
error_color_rgb="255;50;50"
error_color_rgb="255;62;92"
warn_prefix_color_rgb="255;106;50"
warn_color_rgb="255;161;50"

on_exit() {
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${prefix}]\x1b[1;38;2;${warn_color_rgb}m\n${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[${script_name} warn at ${linenum}]" "${@}"
}

error() {
    local -- linenum="${BASH_LINENO[1]}"
    error_prefixed "[${script_name} error at ${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${prefix}]\x1b[1;38;2;${error_color_rgb}m\n${message}\x1b[0m"
}

process_argv() {
    repl no echo
    if [ ${argc} -eq 0 ]; then
        exit_error "missing argument: <ARGUMENT>"
        exit 1
    fi
    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
        local -- tmp_url=""
        # if tmp_url=$(grep -i -E '^https://([^/]+[/]?)+([?#].*)$' <<< "${arg}") && [ -n "${tmp_url}" ]; then
        local -- regex='^(https:\/\/)(([^\/]+[\/]?)+)([?#].*)?$'
        if tmp_url=$(grep -i -E "${regex}" <<< "${arg}"); then
            # echo -e "\x1b[1;38;5;231m${tmp_url}\x1b[0m"
            # sed -E "s/${regex}/\1\x1b[1;38;5;220m\2\x1b[0m\3\4/g" <<< "${tmp_url}"
            # continue
            if [ -z "${ppv_url}" ]; then
                ppv_url="${tmp_url}"
            else
                warn_prefixed "ignoring extra url ${arg@Q}" "pay-per-view url already set to ${ppv_url@Q}"
            fi
        else
            warn_prefixed "argument ${current} of ${argc}" "skipping invalid url: ${arg}"
        fi
    done
    repl sane
}

main() {
    open "https://archive.ph/${ppv_url}"
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    process_argv ${argv[@]}
    main
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
