#!/usr/bin/env bash

declare -a vars_to_ignore=($(2>&1 declare | sed -n 's/^\([A-Z0-9_]\+\)=.*/^\1=/gp') "vars_to_ignore")
declare -i vars_to_ignore_count=${#vars_to_ignore[@]}

dump_vars() {
    local ignore_regexp="($(for index in ${!vars_to_ignore[@]}; do
        current=$(($index + 1))
        var=${vars_to_ignore[$index]}
        if [ ${vars_to_ignore_count} -eq 1 ] || [ ${current} -eq ${vars_to_ignore_count} ]; then
            echo "${var}"
        else
            echo -n "${var}|"
        fi
    done))="
    # echo ${ignore_regexp@A}
    # exit 1
    if 1>/dev/random 2>/dev/random which bash-vars-to-json; then
        2>&1 declare | ack '^[a-z0-9_]+=' | ack -vi "${ignore_regexp}" | bash-vars-to-json
    else
        2>&1 declare | ack '^[a-z0-9_]+=' | ack -vi "${ignore_regexp}"
    fi
}
declare -x TZ=UTC
declare -i MAX_FILENAME_LENGTH=220

set -e
set -o pipefail
export IFS=$'\n'

this_script_path="${BASH_SOURCE[0]}"
script_name="$(basename "${this_script_path}")"
script_path="$(dirname "${this_script_path}")"

declare -a argv=($@)
declare argc=${#argv[@]}

declare -a report_words=()
declare -i report_words_count=0
declare -a target_path_slug_chunks=()
declare -i target_path_slug_chunks_count=0
declare -a extra_opts=()
declare -i extra_opts_count=0
declare concatenated_slug_chunks=""
declare -i concatenated_slug_chunks_count=0

declare report_target_base_path="$HOME/freeze-reports/$(today)"
declare report_target_path=""

error_prefix_color_rgb="$((0xFF));$((0x00));$((0x42))"
error_color_rgb="$((0xFF));$((0x32));$((0x32))"
error_color_rgb="$((0xFF));$((0x3E));$((0x5C))"
warn_prefix_color_rgb="$((0xFF));$((0x6A));$((0x32))"
warn_color_rgb="$((0xFF));$((0xA1));$((0x32))"

on_exit() {
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn() {
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m[${script_name} warn]\x1b[1;38;2;${warn_color_rgb}m ${@}\x1b[0m"
}
error() {
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m[${script_name} error]\x1b[1;38;2;${error_color_rgb}m ${@}\x1b[0m"
}

process_argv() {
    repl no echo
    if [ ${argc} -eq 0 ]; then
        exit_error "missing argument: <ARGUMENT>"
        exit 1
    fi
    for index in ${!argv[@]}; do
        current="$(($index + 1))"
        arg="${argv[$index]}"
        if [ -z "${arg}" ]; then
            warn "skipping arg ${current}/${argc}: empty string"
            continue
        fi
        arg_slug="$(slugify-string "${arg}")"
        if [ -z "${arg_slug}" ]; then
            warn "skipping arg ${current}/${argc}: effectively empty string"
            continue
        fi

        case "${arg}" in
            -*)
                if [ $index -eq 0 ]; then
                    exit_error "invalid first argument: ${arg}"
                fi
                extra_opts+=("${arg}")
                ;;
            *)
                report_words+=("${arg}")
                ;;
        esac

        target_path_slug_chunks_count=${#target_path_slug_chunks[@]}
        if [ ${target_path_slug_chunks_count} -gt 0 ]; then
            concatenated_slug_chunks="$(slugify-string "${target_path_slug_chunks[@]}")"
        fi
        concatenated_slug_chunks_count=${#concatenated_slug_chunks}
        if [ $((${#concatenated_slug_chunks} - ${#arg_slug})) -lt ${MAX_FILENAME_LENGTH} ]; then
            target_path_slug_chunks+=("${arg_slug}")
            target_path_slug_chunks_count=${#target_path_slug_chunks[@]}
            concatenated_slug_chunks="$(slugify-string "${target_path_slug_chunks[@]}")"
            concatenated_slug_chunks_count=${#concatenated_slug_chunks}
        else
            warn "skipping slug ${arg_slug@Q} because target filename already long enough: ${concatenated_slug_chunks}"
        fi
    done
    target_path_slug_chunks_count=${#target_path_slug_chunks[@]}
    concatenated_slug_chunks_count=${#concatenated_slug_chunks}
    report_words_count=${#report_words[@]}
    extra_opts_count=${#extra_opts[@]}
    repl sane
}

main() {
    if [ ${extra_opts_count} -gt 0 ]; then
        warn "${extra_opts_count} extra_opts passed as argument"
        for index in ${!extra_opts[@]}; do
            param="${extra_opts[$index]}"
            warn "    extra_opts[$index] ${param@Q}"
        done
    fi

    if [ ${report_words_count} -eq 0 ]; then
        exit_error "missing arguments: words to report"
    fi

    mkdir -p "${report_target_base_path}"

    created_at="$(date +"%Y/%m/%d %H:%M:%S %Z")"
    created_at_safe="$(date +"%Y-%m-%d_%H-%M-%S_%Z")"
    created_at_slug="${created_at_safe@L}"
    title="Freeze Report @ ${created_at}"
    slug=$(slugify-string "${title}")
    declare -A metadata=(
        ["title"]="${title}"
        ["slug"]="${slug}"
        ["created_at"]="${created_at}"
    )
    markdown_meta="---\n$(for key in ${!metadata[@]}; do
        declare value="${metadata[$key]}"
        declare field="${key}: ${value}\n"
        echo -n "${field}"
    done)\n---\n"
    head="${markdown_meta}\n# ${title}\n\n"
    vardump="\n\n### VARDUMP\n\n \`\`\`\n$(dump_vars | sed 's/^/# /g')\n\`\`\`\n"
    body="${report_words[@]}\n${vardump}\n"

    report_target_path="${report_target_base_path}/${created_at_slug}-${concatenated_slug_chunks}.md"

    mkdir -p "$(dirname "${report_target_path}")"
    content=(echo -e "${head}\n\n${body}\n")
    echo "${content[@]}" >"${report_target_path}"
    1>&2 echo -e "reported to ${report_target_path@Q}"
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    process_argv ${argv[@]}
    main
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
