#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -g script_name="$(basename "${BASH_SOURCE[0]}")"
declare -g script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -g this_script_path="${script_path}/${script_name}"

on_exit() {
    set +x
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}

declare -i code=0

declare -i current=0
declare -g rg=""
declare -g pos=""

declare -i index=0
declare -g rg=""
declare -g param=""

declare -i next_index=0
declare -g next_arg=""
declare -g next_param=""

declare -i skip_next=0

declare -i lineno=0
declare -i line_number=0
declare -g line=""

declare -g argument=""
declare -g field=""
declare -g key=""
declare -g name=""
declare -g path=""
declare -g value=""

declare -gi start_of_day=$(date -d 'today 00:00:00' +%s)
declare -g hex_sod=$(builtin printf '%010x' ${start_of_day})
declare -gi now=$(date -u +'%s')
declare -g now_hex=$(builtin printf '%010x' ${now})
declare -g userland_username="gabrielfalcao"
declare -g userland_home="/Users/gabrielfalcao"

declare -g log_folder="${userland_home}/workbench/$(date --date=@${now} +'%Y-%m-%d')/rsync-forensic-from-to-${hex_sod}"
mkdir -p "${log_folder}"

declare -g hex_pid=$(builtin printf '%08x' $$)
declare -g hex_ppid=$(builtin printf '%08x' ${PPID})
declare -g log_name=$(heck-string --to=kebab "${argv[@]}")

declare -g artifact_suffix="${hex_pid}.${hex_ppid}.${hex_sod}"
declare -g stderr="${log_folder}/${log_name}.stderr.${artifact_suffix}.log"
declare -g stdout="${log_folder}/${log_name}.stdout.${artifact_suffix}.log"
declare -i code=0
declare -a rsync_call_args=(
    rsync
    --info=name
    -gpuacvot
    --stats
    --fsync
    --mkpath
    --ignore-errors
    --progress
    --info=progress2,stats2,misc1,flist0
    --log-file="${log_folder}/${log_name}.log"
    --log-file-format='%i %n%L'
)

main() {
    if [ ${argc} -eq 0 ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "missing arguments: <FROM> <TO>"
    fi
    if [ ${argc} -ne 2 ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "wrong number of arguments, ${script_name} takes exactly 2 arguments but received ${argc}"
        exit 1
    fi
    local -- from="${argv[@]:0:1}"
    local -- to="${argv[@]:1:1}"

    local -- orig_input_from="${from}"
    local -- orig_input_to="${to}"

    if [[ "${from}" =~ ^(([A-Za-z0-9.,_/-]+)([^/]+))([/]*)$ ]] && [[ -v BASH_REMATCH[1] ]]; then
        from="${BASH_REMATCH[1]}"
    fi
    if [[ "${to}" =~ ^(([A-Za-z0-9.,_/-]+)([^/]+))([/]*)$ ]] && [[ -v BASH_REMATCH[1] ]]; then
        to="${BASH_REMATCH[1]}"
    fi

    local -- value_from="$(tr -d '[:space:]' <<<"${from}")"
    local -- value_to="$(tr -d '[:space:]' <<<"${to}")"

    if [ -z "${value_from}" ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "argument <FROM> is not a valid path: ${from@Q}"
        exit 1
    elif [ ! -e "${from}" ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "value of argument <FROM> should point to an existing directory but ${from@Q} does not exist"
        exit 1
    elif [ ! -d "${from}" ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "value of argument <FROM> should point to an existing directory but ${from@Q} is a $(gstat -c '%F' "${from}")"
        exit 1
    fi

    if [ -z "${value_to}" ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "argument <TO> cannot be empty: ${to@Q}"
        exit 1
    elif [ -e "${to}" ]; then
        1>&2 echo -e "[$(basename "${BASH_SOURCE[0]}") error]" "value of argument <TO> cannot be an existing path but ${to@Q} is a $(gstat -c '%F' "${to}")"
        exit 1
    fi

    log_name=$(heck-string --to=kebab "${from}")

    artifact_suffix="${hex_pid}.${hex_ppid}.${hex_sod}"
    stderr="${log_folder}/${log_name}.stderr.${artifact_suffix}.log"
    stdout="${log_folder}/${log_name}.stdout.${artifact_suffix}.log"

    rsync_call_args+=("${from}/")
    rsync_call_args+=("${to}/")

    debug_vars argc argv from orig_input_from orig_input_to rsync_call_args to value_from value_to
}

# ^\s-+[#][A-F0-9]\{6\}\s-+\(\([a-z[:space:]]+\)\(medium\|light\|dark\)\)\s-+\([\\]x1b[[]1;38;2;\)\(\(\([0-9]\|[1][0-9]\{1,2\}\|[2][0-5][0-5]\|[2][0-4][0-9]\)\);\)\(\(\([0-9]\|[1][0-9]\{1,2\}\|[2][0-5][0-5]\|[2][0-4][0-9]\)\);\)\(\(\([0-9]\|[1][0-9]\{1,2\}\|[2][0-5][0-5]\|[2][0-4][0-9]\)\)\) → \,(regex!)
debug_vars() {
    local -a var_names=($@)
    local -i total_varnames=${#var_names[@]}
    local -i index=0
    local -i current=0
    local -- name=""
    local -- pos=""

    if [ ${total_varnames} -eq 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]" "missing arguments: [...VARNAMES]"
        return 1
    fi
    local -a bright_colors=(

        #FCE94F yellow light            \x1b[1;38;2;252;233;79m
        #EDD400 yellow medium           \x1b[1;38;2;237;212;0m
        #FCAF3E orange light            \x1b[1;38;2;252;175;62m
        #F57900 orange medium           \x1b[1;38;2;245;121;0m
        #8AE234 green light             \x1b[1;38;2;138;226;52m
        #73D216 green medium            \x1b[1;38;2;115;210;22m
        #3465A4 sky blue medium         \x1b[1;38;2;52;101;164m

    )
    local -a dark_colors=(
        #555753 aluminum dark medium    \x1b[1;38;2;85;87;83m
        #2E3436 aluminum dark dark      \x1b[1;38;2;46;52;54m

    )



    for index in ${!var_names[@]}; do
        current=$(($index + 1))
        name="${var_names[$index]}"
        pos="$(printf '%*s of %s' ${#total_varnames} ${current} ${total_varnames})"

        if [[ ! -v "${name}" ]]; then
            1>&2 echo -e "[${FUNCNAME[0]} error]" "value of argument ${pos} is not the name of an existing global variable"
            return 404
        fi

        if [[ -v refvar ]]; then
            unset -n refvar
        fi

        local -I -n refvar="${name}"
        1>&2 echo -en "\x1b[1;38;2;46;52;54m\x1b[1;48;2;252;233;79mVARIABLE:\x1b[0m\x1b[1;38;2;46;52;54m\x1b[1;48;2;252;233;79m\x1b[7m${refvar[@]@Q}\x1b[0m\n"
        # 1>&2 echo -en "\x1b[1;38;2;245;121;0m"
        unset -n refvar
    done
}
if [ "${0}" == "${BASH_SOURCE[0]}" ]; then

    1>&2 echo -e "\n\x1b[2J\x1b[3J\x1b[H\n"
    declare -p argv argc
    main
    1>&2 echo -e "\n\n"
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi

# ^\\s-*\\([#]\\([A-F0-9]\\{2\\}\\)\\([A-F0-9]\\{2\\}\\)\\([A-F0-9]\\{2\\}\\)\\)\\s-+\\(\\([a-z[:space:]]+\\)\\(medium\\|light\\|dark\\)\\)\\s-+\\([\\\\]x1b[[]1;[43]8;2;\\)\\(\\([0-9]\\{1,3\\}\\)[;]\\)\\(\\([0-9]\\{1,3\\}\\)[;]\\)\\(\\([0-9]\\{1,3\\}\\)[m]\\)
# ^\s-*\([#]\([A-F0-9]\{2\}\)\([A-F0-9]\{2\}\)\([A-F0-9]\{2\}\)\)\s-+\(\([a-z[:space:]]+\)\(medium\|light\|dark\)\)\s-+\([\\]x1b[[]1;[43]8;2;\)\(\([0-9]\{1,3\}\)[;]\)\(\([0-9]\{1,3\}\)[;]\)\(\([0-9]\{1,3\}\)[m]\) → \,(let* (\n  (rgb-hex-code \1) \n  (hex-red \2)\n  (hex-green \3)\n  (hex-blue \4)\n  (color-name \5)\n  (color-tone \6)\n  (ansi-truecolor-red (match-string 10))\n  (ansi-truecolor-green (match-string 11))\n  (ansi-truecolor-blue (match-string 12))  ))

# 0=`        #FCE94F yellow light            \x1b[1;38;2;252;233;79m`
# 1=`#FCE94F`
# 2=`FC`
# 3=`E9`
# 4=`4F`
# 5=`yellow light`
# 6=`yellow `
# 7=`light`
# 8=`\x1b[1;38;2;`
# 9=`252;`
# 10=`252`
# 11=`233;`
# 12=`233`
# 13=`79m`
# 14=`79`

# 0=`        #2E3436 aluminum dark dark      \x1b[1;38;2;46;52;54m`
# 1=`#2E3436`
# 2=`2E`
# 3=`34`
# 4=`36`
# 5=`aluminum dark dark`
# 6=`aluminum dark `
# 7=`dark`
# 8=`\x1b[1;38;2;`
# 9=`46;`
# 10=`46`
# 11=`52;`
# 12=`52`
# 13=`54m`
# 14=`54`
