#!/usr/bin/env bash

. ${HOME}/opt/lib/ansi.sh

for project_path in $(find-rust-projects ${HOME}/projects); do
    toolchain_config_display=$(get_display_path "${toolchain_config}")
    project_path_display=$(get_display_path "${project_path}")
    toolchain_config="${project_path}/rust-toolchain.toml"
    if [ ! -e "${toolchain_config}" ]; then
        1>&2 bar_text_left 231 16 "skipping rust project missing rust-update-toolchain.toml: $(ansi 16 231 "${project_path_display}")"
        continue
    fi

    if git_repo_path=$(2>/dev/null 1>/dev/null cd "${project_path}" && 2>/dev/random git rev-parse --show-toplevel); then
        if toolchain_config_git_changed=$(2>/dev/null 1>/dev/null cd "${project_path}" && 2>/dev/random git status --porcelain | grep '^[A-Za-z]\+[[:space:]]\+rust-toolchain[.]toml$'); then
            if [ -z "${toolchain_config_git_changed}" ]; then
                if (cd "${project_path}" && bar_text_left 231 27 "updating toolchain_config ${toolchain_config}" && sed 's/^channel[[:space:]]*=[[:space:]]*"nightly-2025-04-16"/channel = "nightly-2025-09-09"/g' -i Cargo.toml); then
                    bar_text_left 82 16 "updated $(ansi_spaced 16 82 "${toolchain_config_display}")"
                    if (cd "${project_path}" && git add Cargo.toml && git commit Cargo.toml -m 'channel="nightly-2025-09-09"'); then
                        ansi_up
                        bar_text_left 82 16 "updated $(ansi_spaced 16 82 "${toolchain_config_display}") $(ansi_spaced 82 16 "git")"
                    fi
                else
                    bar_text_left 231 196 "failed to update $(ansi_spaced 16 82 "${toolchain_config_display}")"
                fi
            else
                1>&2 bar_text_left 202 16 "skipping git-modified ${toolchain_config_display}"
            fi
        elif sed 's/^channel[[:space:]]*=[[:space:]]*"nightly-2025-04-16"/channel = "nightly-2025-09-09"/g' -i ${toolchain_config}; then
            1>&2 bar_text_left 154 16 "updated: $(ansi 16 231 "${toolchain_config}")"
        fi
    else
        1>&2 bar_text_left 231 16 "skipping non-git directory: $(ansi 16 231 "${project_path_display}")"
    fi
done
