#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -- this_script_path="${script_path}/${script_name}"
declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -a stdin_lines=(${@})
declare -i stdin_line_count=${#stdin_lines[@]}
declare -- git_repo_path=""
declare -i code=0
declare -i argv_return_code=0
declare -i stdin_return_code=0

declare -- curdir="$PWD"
if [ -z "${PWD}" ]; then
    curdir=$(pwd)
fi

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty "${stty_args[@]}"
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ "$BASH_TRACE" = "" ] && [ "$BASH_LOGLEVEL" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -i index=0
declare -i current=0
declare -- arg=""
declare -- path=''
declare -- crate_path=''
declare -- manifest_path=''
declare -A manifest_path_to_crate_map=()
declare -- pos=''

process_argv() {
    crate_path="$(pwd)"
    manifest_path="${crate_path}/Cargo.toml"

    if [ ${argc} -eq 0 ]; then
        if [ -f "${manifest_path}" ] && [ -s "${manifest_path}" ]; then
            manifest_path_to_crate_map["${manifest_path}"]="${crate_path}"
            return
        fi
        1>&2 echo -e "[${BASH_SOURCE[0]} error]" "missing arguments: <PATH(S) TO RUST CRATE OR MANIFEST>"
        exit 1
    fi

    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
        pos=$(printf '%*s of %s' ${#argc} ${current} ${argc})

        crate_path=''
        manifest_path=''

        if [ ! -e "${arg}" ]; then
            1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid arg ${pos}: not an existing path"
            continue
        fi

        path="$(path canon "${arg}")"

        if [ -d "${path}" ]; then
            crate_path="${path}"
            manifest_path="${crate_path}/Cargo.toml"
            if [ ! -e "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: no manifest at ${manifest_path@Q}"
                continue
            elif [ ! -r "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: unreadable file ${manifest_path@Q}"
                continue
            elif [ ! -s "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: empty file ${manifest_path@Q}"
                continue
            fi
        elif [[ "${path}" =~ Cargo[.]toml$ ]]; then
            manifest_path="${path}"
            crate_path="$(path parent "${path}")"
            if [ ! -e "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: no manifest at ${manifest_path@Q}"
                continue
            elif [ ! -r "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: unreadable file ${manifest_path@Q}"
                continue
            elif [ ! -s "${manifest_path}" ]; then
                1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid crate path in arg ${pos}: empty file ${manifest_path@Q}"
                continue
            fi
        else
            1>&2 echo -e "[${BASH_SOURCE[0]} warning]" "ignoring invalid arg ${pos} ${arg@Q}: unrecognized path type"
            continue
        fi
        manifest_path_to_crate_map["${manifest_path}"]="${crate_path}"
    done
}

main() {
    1>&2 echo -en "\x1b[2J\x1b[3J\x1b[H"
    local -- subpid=-1

    for manifest_path in ${!manifest_path_to_crate_map[@]}; do
        crate_path="${manifest_path_to_crate_map[${manifest_path}]}"
        (pushd "${crate_path}" && 1>tmp.cargo-cbt.stdout.log 2>tmp.cargo-cbt.stderr.log time -o tmp.cargo-cbt.timing cargocbtallsafe) &
        subpid=$!
        disown -a
        info_prefixed "[manifest ${manifest_path}]" "started background build: pid ${subpid}"
    done
}
if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_argv "${argv[@]}"; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
