#!/usr/bin/env bash
# shellcheck disable=SC2004,SC2206,SC2068,SC2086

set -e
set -o pipefail
export IFS=$'\n'

declare -a argv=($@)
declare argc=${#argv[@]}

declare -a directory_argv=()
declare -a non_path_params=()
declare -a result_file_paths=()
declare -a result_file_and_linenumbers=()
declare default_regexp='struct\s+(Workspace|WorkSpace|Package|Manifest)'
declare regexp=""

error_color_rgb="$((0xFF));$((0x00));$((0x42))"
warn_color_rgb="$((0xFF));$((0x6A));$((0x32))"

on_exit() {
    repl sane
}
on_ctrlc() {
    repl no echo
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    repl sane
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sigsys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <PATH>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}
warn() {
    1>&2 echo -e "\x1b[1;38;2;${warn_color_rgb}m[warn] ${@}\x1b[0m"
}
error() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m[error] ${@}\x1b[0m"
    exit 1
}
process_argv() {
    repl no echo
    # if [ ${argc} -eq 0 ]; then
    #     1>&2 echo -e "missing argument: <PATH>"
    #     usage
    #     repl sane
    #     exit 1
    # fi
    for arg in ${argv[@]}; do
        if [ -f "${arg}" ]; then
            exit_error "invalid argument not a directory: ${arg@Q}"
        elif [ -d "${arg}" ]; then
            directory_argv+=("${arg}")
        elif [ ! -e "${arg}" ]; then
            non_path_params+=("${arg}")
        else
            exit_error "invalid not a directory: ${arg@Q}"
        fi
    done
    repl sane

    if [ ${#directory_argv[@]} -eq 0 ]; then
        directory_argv+=("$HOME/projects")
        1>&2 echo -e "no directories provided, defaulting to ${directory_argv[@]@Q}"
    fi
    if [ ${#non_path_params[@]} -eq 0 ]; then
        non_path_params+=("${default_regexp}")
        warn "no regular expression provided, defaulting to ${non_path_params[@]@Q}"
    elif [ ${#non_path_params[@]} -gt 1 ]; then
        1>&2 echo -e "[error] too many regular expresions provided:"
        for index in ${non_path_params[@]}; do
            regexp=${non_path_params[$index]}
            1>&2 echo -e "\t$(($index + 1)): ${regexp@Q}"
        done
        exit 1
    fi
    regexp="${non_path_params[0]}"
}
search_latest_rust_file_matching() {
    search_path=${1}
    if [ -z "${search_path}" ]; then
        1>&2 echo "[search_latest_rust_file_matching error]: missing argument <PATH>"
        return 1
    fi
    local -a matching_files=($(ack --rs -l "${regexp}" "${search_path}"))
    for rs_file in ${matching_files[@]}; do
        rs_dirname=$(dirname ${rs_file})
        if git_repo=$(2>/dev/random 1>/dev/random cd ${rs_dirname} && git rev-parse --show-toplevel); then
            if [ -n "${git_repo}" ] && [ -d "${git_repo}" ]; then
                declare -a cargo_manifests=($(find "${git_repo}" -type f -name Cargo.toml))
                for manifest in ${cargo_manifests[@]}; do
                    manifest_directory=$(dirname "${manifest}")
                    if [ -n "$(grep -i '\btoml\b' ${manifest})" ]; then
                        for filename_and_lineno in $(ack --rs --no-filename "${regexp}" --output='$f:$.' "${manifest_directory}"); do
                            result_file_paths+=("$(sed -n 's/:[0-9]\+\s*$//gp' <<< "${filename_and_lineno}")")
                            result_file_and_linenumbers+=("${filename_and_lineno}")
                        done
                    fi
                done
            fi
        fi
    done
}
main() {
    local -i directory_count=${#directory_argv[@]}
    for index in ${!directory_argv[@]}; do
        directory="${directory_argv[$index]}"
        search_latest_rust_file_matching ${directory}
    done
    local -i result_count=${#result_file_paths[@]}

    if [ ${result_count} -eq 0 ]; then
        exit_error "no matches in ${directory_argv[@]@Q}"
    else
        # echo -e "\x1b[1;38;5;220mRESULT\x1b[0m"
        cwd=$(pwd)
        for path in ${result_file_paths[@]}; do
            echo ${path};
        done | sort -u | xargs ls -ltrh | sed -n "s/${cwd//\//\\\/}/./gp" | sed -n 's/^\([^ ]\+\s\+\)\{4\}//gp'
    fi

}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    process_argv ${argv[@]}
    main
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
