#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -i total_groups=-1
declare -- arg_value=""
declare -- key=""
declare -- value=""
declare -- field=""
declare -- val=""

display_array() {
    local -a argv=($@)
    local -i argc=${#argv[@]}
    local -i index=0
    local -i current=0
    local -- arg=""

    if [ ${argc} -eq 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]" "missing argument: <ARRAY_VARIABLE_NAME>"
        return 1
    fi
    local -- varname_whole_argv="${@}"
    local -- varname_each_arg=""
    local -i varname_each_idx=0;

    if [[ -v "${varname_whole_argv}" ]]; then
        local -I -n refvar_whole_argv="${varname_whole_argv}"
        local -- ty_refvar_whole_argv="${refvar_whole_argv[@]@a}"
        local -- ty_name_long=""
        case "${ty_refvar_whole_argv}" in
            "a")
                ty_name_long="array"
                ;;
            "A")
                ty_name_long="map"
                ;;
            "i")
                ty_name_long="integer"
                ;;
            "i")
                ty_name_long="integer"
                ;;
        esac

        1>&2 echo -e "[${FUNCNAME} varname_whole_argv]" "${varname_whole_argv} ${ty_refvar_whole_argv@Q}"
    fi

    if [ ${#} -eq 0 ]; then
    fi

    for key in ${!argv[@]}; do if [[ "${argv[${key}]}" =~ ^[0-9]+$ ]]; then value=$(( argv[${key}] )) printf '\t%*s => %s\n' "${#argc}" "${key}"
}


if [ ${argc} -eq 0 ]; then
    1>&2 echo -e "[${script_name} error]"  "missing argument: <TOTAL_GROUPS>"
    exit 1
elif [ ${argc} -ge 2 ]; then

    1>&2 echo -e "[${script_name} error]"  "tool takes exactly 1 argument <TOTAL_GROUPS>, received ${argc} arguments instead:\n$(display_array argv)"
    # 1>&2 declare -p argv
    exit 1
else
    arg_value="${argv[@]}"
fi
declare -i seq_min=1
declare -i seq_max=0

####
####
####  ___ _____ ___  ___ _
#### / __|_   _/ _ \| _ \ |
#### \__ \ | || (_) |  _/_|
#### |___/ |_| \___/|_| (_)
####
####
####
####
#### __      _____ ___ _____ ___     _     ___ ___ ___ _____  __  ___  _   ___  ___ ___ ___     _   _  _ ___    ___ ___ ___ _  _ _____
#### \ \    / / _ \_ _|_   _| __|   /_\   | _ \ __/ __| __\ \/ / | _ \/_\ | _ \/ __| __| _ \   /_\ | \| |   \  | _ \ _ \_ _| \| |_   _|
####  \ \/\/ /|   /| |  | | | _|   / _ \  |   / _| (_ | _| >  <  |  _/ _ \|   /\__ \ _||   /  / _ \| .` | |) | |  _/   /| || .` | | |
####   \_/\_/ |_|_\___| |_| |___| /_/ \_\ |_|_\___\___|___/_/\_\ |_|/_/ \_\_|_\|___/___|_|_\ /_/ \_\_|\_|___/  |_| |_|_\___|_|\_| |_|
####
####
####  _  _ _   _ __  __ ___ ___ ___    ___  ___    ___ ___  ___  _   _ ___     _   ___ _____   _  _  ___  ___  ___ ___
#### | \| | | | |  \/  | _ ) __| _ \  / _ \| __|  / __| _ \/ _ \| | | | _ \   /_\ / __|_   _| | \| |/ _ \|   \| __/ __|
#### | .` | |_| | |\/| | _ \ _||   / | (_) | _|  | (_ |   / (_) | |_| |  _/  / _ \\__ \ | |   | .` | (_) | |) | _|\__ \
#### |_|\_|\___/|_|  |_|___/___|_|_\  \___/|_|    \___|_|_\\___/ \___/|_|   /_/ \_\___/ |_|   |_|\_|\___/|___/|___|___/
####
####
####  ___ _  _ ___ _____ ___   _   ___  _
#### |_ _| \| / __|_   _| __| /_\ |   \| |
####  | || .` \__ \ | | | _| / _ \| |) |_|
#### |___|_|\_|___/ |_| |___/_/ \_\___/(_)
####
#### # declare -r no_group_chars_within_open_close_parens_syntax='([(]([^()|]*)[)])'
#### # declare -r no_group_chars_fallback_syntax='([(](.*?)[)])'
#### # declare -r no_group_syntax='[(]([^()|]*|[(][^()|]+[)]|[(](.*)[)])[)]'
#### # declare -r no_group_syntax='^(.*?([^(|)]*[(]([^()|]*|[(][^()|]+[)]|[(](.*)[)])[)][^(|)]*).*?)+$'
#### # declare -r detect_group_count_regexp='^(.*?([^(|)]*[(]([^()|]*|[(][^()|]+[)]|[(](.*)[)])[)][^(|)]*).*?)+$'
#### # arg_value="${argv[0]}"


if [[ ! "${arg_value}" =~ ^[1-9][0-9]*$ ]]; then
    1>&2 echo -e "[${script_name} error]"  "invalid positive integer in command-line argument: ${arg_value@Q}"
    exit 1
fi

seq_max=${arg_value}
declare -i tty_in=0;
declare -i tty_out=0;

if [ -t 0 ]; then
    tty_in=1
fi
if [ -t 1 ]; then
    tty_out=1
fi

if (( $tty_out )); then
    1>&2 echo -en "\n"
fi

extract_number_from_line() {
    if [ ${#} -lt 1 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]"  "missing argument: <STRING_WITH_NUMBER(S)>"
        return 1
    fi
    local -- line="$(printf '\n%s\n' ${@})"

    local -a numbas=()
    local -A numba_map=()
    local -- tmpraw=()
    local -i tmpno=()
    local -i line_index=0
    local -a input_numbas=( $(sed -z -E 's/([0-9]+)/\n\1\n/gp' <<< "${raw_input}") )
    local -a input_nonumbas=( $(sed -z -E 's/[^0-9]+/\n\1\n/gp' <<< "${raw_input}") )

    1>&2 local -p

    # for tmpraw in ; do
    #     tmpno=$(( tmpraw ))

    #     if [ "${tmpraw}" == "${tmpno}" ]; then
    #         numba_map[${tmpno}]=${line_index}
    #         numas+=("${tmpno}")
    #     else
    #     fi
    # done

}
gen_subexpr_rep() {
    local -a argv=($@)
    local -i argc=${#argv[@]}
    local -i index=0
    local -i current=0
    local -- arg=""
    local -a params=()
    local -i param_count=${#params[@]}

    if [ ${argc} -le 0 ] && [ -t 0 ]; then
        1>&2 echo -e "[${FUNCNAME[0]} error]"  "missing argument: <SUB_EXPRESSION_NUMBER>"
        return 1
    fi

    local -a numbas=()
    local -A numba_map=()
    local -- tmpraw=()
    local -i tmpno=()
    local -i line_index=0

    if [ ! -t 0 ]; then
        export IFS=$'\n'
        while read line; do
            extract_number_from_line "${line}"
            line_index=$(( line_index + 1 ))

            1>&2 echo -e "\x1b[1;38;5;220m$(local -p)\x1b[0m"
            # if [[ "${line}" =~ (([^0-9]*)([0-9]+)([0-9]*))+ ]]; then
            #     for tmpraw in $(sed -z -E 's/[^0-9]+/\n/g' <<< "${line}"); do
            #         tmpno="${tmpraw}"
            #         if [[ ! -v numba_map[${tmpno}] ]]; then
            #             numba_map[${tmpno}]=${line_index}
            #             numas+=("${tmpno}")
            #         fi
            #     done
            #     line_index=$(( line_index + 1 ))
            #     break
            # fi
        done </dev/stdin
    fi


    # if [ ${#} -le 0 ]; then
    #     1>&2 echo -e "[${FUNCNAME[0]} error]"  "missing argument: <SUB_EXPRESSION_NUMBER>"
    #     return 1
    # elif [ ${#} -gt 1 ]; then
    #     1>&2 echo -e "[${FUNCNAME[0]} error]"  "received ${#} arguments but takes exactly 1 argument: <SUB_EXPRESSION_NUMBER>\n\rarguments: $(printf '%s, ' ${@} | sed -E 's/[,]\s*$//g')"
    #     return ${#}
    # fi


    # subexpr_raw="${1}"
    # subexpr="${subexpr_raw}"

    # if [ ${subexpr} -lt 0 ]; then
    #     1>&2 echo -e "[${FUNCNAME[0]} error]"  "invalid argument for SUB_EXPRESSION_NUMBER, negative number: ${subexpr@Q}"
    #     return ${#}
    # fi
    # sed -E 's/^\s*([0-9]+)\s*$/\\n\1=\\\1\\n/g' <<< "${subexpr}"
}


# echo -e '\n<0>'
# echo -e '\n</0>'


declare -- tmpval=''
declare -i tmpnum=-1

for tmpval in $(seq ${seq_min} ${seq_max}); do
    gen_subexpr_rep ${tmpval} #  | sed -z  -E 's/[\n]/\\n/g'
done

if (( $tty_out )); then
    1>&2 echo -e "\n"
fi
