#!/usr/bin/env bash

declare -r ifs_lb=$'\n'
declare -r ifs_old=${IFS:-${ifs_lb}}
export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
export IFS="${ifs_old}"

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -- this_script_path="${script_path}/${script_name}"
declare -a argv=("$@")
declare -i argc=${#argv[@]}
declare -i code=0
declare -a sed_params=()
declare -a sed_commands=()
declare -A potential_sed_expressions=()
declare -- sed_expression=""
declare -- curdir="$PWD"

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty "${stty_args[@]}"
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ "$BASH_TRACE" = "" ] && [ "$BASH_LOGLEVEL" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}
declare -a sed_match_expression_regexps=()
declare -A sed_match_expression_regexps_unique=()

declare -a sed_quote_command_regexps=()
declare -A sed_quote_command_regexps_unique=()

quote_regexp() {
    local -- regex="$@";
    if [ -z "${regex}" ]; then
        return 1;
    fi
    local -- result="${regex}";
    local -a regexes=();
    local -A replacements_by_regex=();
    replacements_by_regex['\\(.\\)']='[\\1]';
    replacements_by_regex['[[]\\([\\]\\|[\\\\]\\|[\\^]\\|[\\$]\\)[]]']='\\1';
    replacements_by_regex['[[] []]']='[[:space:]]';
}
extract_groups() {
    local -- regex="$@";
    if [ -z "${regex}" ]; then
        return 1;
    fi
    local -a regexes=();
    regexes+=('[\\]{2}') # regexes["[\\]{2}"]="____";
    regexes+=('[\\][()]') # regexes["([\\][()])"]="__";
    regexes+=('[[][()][]]') # regexes["([[][()]+[]])"]="___";
}

add_regexp() {
    local -a ar_argv=($@)
    local -i ar_argc=${#ar_argv[@]}
    local -- regexp=""
    local -- commmand_name=""

    if [ ${ar_argc} -lt 2 ]; then
        # warn_prefixed "[${FUNCNAME[0]} warning]" "missing arguments: <REGEXP CATEGORY> <REGEXP> <COMMMAND_NAME>"
        warn_prefixed "[${FUNCNAME[0]} warning]" "missing arguments: <REGEXP CATEGORY> <REGEXP>"
        return 1
    fi
    regexp="${ar_argv[0]}"

    if [ ${ar_argc} -lt 3 ]; then
        warn_prefixed "[${FUNCNAME[0]} warning]" "missing arguments: <REGEXP CATEGORY> <REGEXP> <REGEXP LABEL>"
        regexp="${ar_argv[@]}"
    else
        commmand_name="${ar_argv[@]:1}"
    fi

    if [[ ! -v sed_match_expression_regexps_unique["${regexp}"] ]]; then
        sed_match_expression_regexps_unique["${regexp}"]="${commmand_name}"
        sed_match_expression_regexps+=("${regexp}")
    else
        warn_prefixed "[${FUNCNAME[0]} warning]" "regexp already added: ${regexp@Q}"
        return 1
    fi

}

add_regexp match_expression 's(.)(.*)\1(.*)\1([gp;]|[{](.*)[}])' 'substitution'
add_regexp match_expression '([/]|[\\][^/])(.*)\1([;]|[{](.*)[}])' 'match'
add_regexp match_expression '(([/]|[\\][^/])(.*)\2([;d]|[{](.*)[}]))' 'deletion'

process_argv() {
    if [ "$argc" -eq 0 ]; then
        return 1
    fi
    repl no echo

    local -i current=0
    local -i index=0
    local -- arg=""
    for index in "${!argv[@]}"; do
        current=$((index + 1))
        arg="${argv[$index]}"
        case "$arg" in
            -*)
                sed_params+=("${arg}")
                continue
                ;;
            *)
                local -- match=''
                local -- regexp=''
                for regexp in ${sed_match_expression_regexps[@]}; do
                    if match=$(grep -E "${regexp}" <<<"${arg}"); then
                        potential_sed_expressions["${arg}"]="${match}"
                    fi
                done
                ;;
        esac
    done
    repl sane
}

main() {
    info_prefixed "[${script_name}]" "main"
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_inputs "${argv[@]}"; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane

exit

bash --init-file ~/.bashrc  -c "$(base64 -d )"

set -x
function debug_vars_fn() {
    echo -en "\x1b[2J\x1b[3J\x1b[H";

    local -- var="";
    for var in ${debug_vars[@]}; do
        echo -e 'local -I -n external="${var}"';
        local -I -n external="${var}";
        echo -e "${external[@]@A}";
    done

    local -a debug_vars=('group_count' 'regexp' 'sub' 'replace' 'input_string' 'sed_match_expression' 'input_string')
    local -a debug_command=('sed' '-n' '-E' "${sed_match_expression@Q}" '<<<' "{input_string@Q}")
    1>&2 echo -e "${debug_command}"
    sed -n -E "${sed_match_expression}" <<<"{input_string}"
    echo
}
declare -i group_count=5;
declare -- regexp="s(.)(.*)\1(.*)\1([gp;]|[{](.*)[}])";
declare -- sub=$(seq 0 ${group_count} | sed -E 's/^([0-9]+)$/\\n\\n<group:\1>\\\1<\\x2fgroup:\1>\\n\\n/g' | tr -d '\n' | sed -E 's/(^(\\n)+|(\\n)+$)//g');
declare -- replace="${sub}";
declare -- input_string="start aaa foo bar aaa end";
declare -- sed_match_expression="s/${regexp}/${sub}/gp";
declare -- raw_input_string='s/^([A-Z_]+[A-Z0-9_]+)=(.*)$/\n\1\n/g;h;d;g;/(^\s*$|\n\n+)/d;p';
declare -- input_string="$(echo "${raw_input_string}")";
debug_vars_fn;
set +x
