#!/Users/gabrielfalcao/.shell.d/.venv/bin/python3

import sys
import click
import re
import shutil
import os
import json
import math
import subprocess
import urllib
import urllib.parse
import dataclasses

from pprint import pformat
from decimal import Decimal
from datetime import datetime, timedelta, UTC
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Union, Optional, Self
from pathlib import Path
from subprocess import Popen


@click.command()
@click.argument("subexp-count", type=int, required=True)
@click.option("-s", "--separator", type=str, default="/")
def main(subexp_count, separator):
    """
    generates debug string for sed subst command
    """
    if subexp_count < 0:
        raise TypeError(f"invalid natural number: {subexp_count}")
    if subexp_count > 9:
        raise TypeError(
            f"invalid sed subexpression number, greater than 9: {subexp_count}"
        )

    subexp_range = list(range(0, subexp_count + 1))
    indentation = " " * 4
    result = r"\n".join(
        [
            "".join(
                [
                    f"<{num}>",
                    rf"\{num}",
                    # rf"\n{indentation}\\\\{num}",
                    f"</{num}>",
                ]
            )
            for num in subexp_range
        ]
    )
    print(f"\b{result}\b\\n")


if __name__ == "__main__":
    main()
