#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -- sed_bin=$(which -a sed | grep -E gnu-sed | head -1 || which sed)

declare -- this_script_path="${script_path}/${script_name}"

declare -a argv=("$@")
declare -i argc=${#argv[@]}

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}

augment_error_message() {
    local -a argv=($@)
    local -i argc=${#argv[@]}
    local -i exit_code=0
    local -- stderr_path=""
    local -- error_output=""

    if [ ${argc} -ne 2 ]; then
        error_prefixed "[${FUNCNAME[0]} error]" "missing arguments: <EXIT_CODE> <STDERR_FILE_PATH>"
        return 1
    fi
    exit_code=${argv[0]}
    stderr_path=${argv[1]}
    if [ -z "${stderr_path}" ]; then
        error_prefixed "[${FUNCNAME[0]} error: invalid stderr path]" "empty string"
        return 1
    elif [ ! -r "${stderr_path}" ]; then
        error_prefixed "[${FUNCNAME[0]} error: invalid stderr path]" "unreadable file: ${stderr_path}"
        return 1
    elif [ ! -s "${stderr_path}" ]; then
        error_prefixed "[${FUNCNAME[0]} error: invalid stderr path]" "empty file: ${stderr_path}"
        return 1
    fi
    error_output=$(cat "${stderr_path}")
    local -i found=0
    local -i culprit_char_pos=0
    local -i culprit_expression=0
    declare -- regexp='^([^:]+)[:]\s*([-][e])?(\s*(expression)\s*([#]([0-9]+)),?)(\s*(char)\s*(([0-9]+)))\s*[:]\s*([^[:space:]]+.*)$'



# ()   ${1}
# ()     ${2}
# (        ${3}
#  ()        ${4}
#  (           ${5}
#   ()           ${6}
#  )           ${5}
# )        ${3}
# (    ${7}
#  ()    ${8}
#  (       ${9}
#   ()       ${10}
#  )       ${9}
# )    ${7}
# ()   ${8}

# 'query-replace-to-history-variable    # =>   'query-replace-history
# 'query-replace-from-history-variable  # =>   'query-replace-history
# 'query-replace-history                # =>   'nil
# 'regexp-search-ring                   # 'search-ring

$sed_bin -n -E "/${regexp}/{s/${regexp}}"

sed: -e expression #1, char 120: unterminated address regex


}
declare -- stderr=$(mktemp)
declare -i code=-1

if [ ! -t 0 ]; then
    2>${stderr} ${sed_bin} ${argv[@]} </dev/stdin
else
    2>${stderr} ${sed_bin} ${argv[@]}
fi
code=$?

if [ ${code} -ne 0 ]; then
    augment_error_message ${code} ${stderr}
fi
