#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"
declare -- stderr="$(mktemp)"

on_exit() {
    set +x
    bash -c "exec 1>&2;
set -umeTE; set +f; set -o pipefail;
rm -f ${stderr@Q} &
disown -a
"
}

on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 130
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -- arg=""
declare -- argument=""
declare -- field=""
declare -- key=""
declare -- line=""
declare -- name=""
declare -- filename=""
declare -- filename_extension=""
declare -- filename_base=""
declare -- param=""
declare -- path=""
declare -- pos=""
declare -- value=""
declare -i code=0
declare -i current=0
declare -i index=0
declare -i line_number=0
declare -i lineno=0
declare -i skip=0
declare -- email=""
declare -- passphrase=""
declare -- target_secret_key="${HOME}/.ssh/${email}"
declare -- target_public_key="${target_secret_key}.pub"
declare -- target_secret_art="${target_secret_key}.art"
declare -- username=""
declare -- domain=""
declare -- tld=""
declare -- reverse_dns=""

declare -r default_target_directory="${HOME}/.ssh"
declare -- target_directory="${HOME}/.ssh"
declare -- key_type="ed25519" # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
declare -- key_type="ecdsa"   # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa

main() {
    if [ ${argc} -eq 0 ]; then
        1>&2 echo -e "[${script_name} error]" "missing argument: <EMAIL>"
        exit 1
    fi

    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
        pos="$(printf '%*s of %s' ${#argc} ${current} ${argc})"
        if [ -z "${email}" ]; then
            if [[ "${arg}" =~ ^(([a-zA-Z0-9_.+-]+)@([a-zA-Z]+[a-zA-Z0-9._+-]*)[.]([a-zA-Z]+[a-zA-Z0-9-]*))$ ]]; then
                username=${BASH_REMATCH[2]}
                domain=${BASH_REMATCH[3]}
                tld=${BASH_REMATCH[4]}
                email=${BASH_REMATCH[1]}
            else
                1>&2 echo -e "[${script_name} warning]" "ignoring argument ${pos} because email already set to ${email@Q}"
                continue
            fi
        elif [ -n "${email}" ] && [ -d "${arg}" ]; then
            target_directory="$(path canon "${arg}" | sed -z -E 's/[\n]+//g')"
            1>&2 echo -e "[${script_name} warning]" "argument ${pos} set target directory to ${target_directory}"
        fi
    done

    if [ -n "${email}" ] && [ -n "${username}" ] && [ -n "${domain}" ] && [ -n "${tld}" ]; then
        reverse_dns="${tld}.${domain}.${username}"
        target_secret_key="${target_directory}/${reverse_dns}.key"
        target_public_key="${target_secret_key}.pub"
        target_secret_art="${target_secret_key}.art"
    else
        1>&2 echo -e "[${script_name} error]" "aborted due to invalid email"
        return 1
    fi

    if [ -e "${target_secret_key}" ]; then
        1>&2 echo -e "[${script_name} error]" "key already exists: ${target_secret_key@Q}"
        exit 1
    fi
    if [ -e "${target_secret_art}" ]; then
        1>&2 echo -e "[${script_name} error]" "key art already exists: ${target_secret_art@Q}"
        exit 1
    fi
    if [ -e "${target_public_key}" ]; then
        1>&2 echo -e "[${script_name} error]" "public key already exists: ${target_public_key@Q}"
        exit 1
    fi
    local -i proceed=0
    if [ -n "${passphrase}" ]; then
        local -- choice=""
        read -p $(printf "passphrase is not empty, do you wish to proceed?\n[N/y]: ") choice
        case "${choice@L}" in
            n | no | nope)
                proceed=0
                1>&2 echo -e "[${script_name} error]" "aborted due to not confirming passphrase"
                return 1
                ;;
            y | yes | yep | sure)
                proceed=1
                ;;
            *)
                1>&2 echo -e "[${script_name} error]" "invalid choice ${choice@Q}"
                return 1
                ;;
        esac
    else
        proceed=1
    fi

    if [ "${target_directory}" == "${default_target_directory}" ]; then
        local -- choice=""
        read -p $(printf "key will be written to ${target_directory}, do you confirm?\n[N/y]: ") choice
        case "${choice@L}" in
            n | no | nope)
                proceed=0
                1>&2 echo -e "[${script_name} error]" "aborted due to not confirming write to ${target_directory}"
                return 1
                ;;
            y | yes | yep | sure)
                proceed=1
                ;;
            *)
                1>&2 echo -e "[${script_name} error]" "invalid choice ${choice@Q}"
                return 1
                ;;
        esac
    else
        proceed=1
    fi

    if ((${proceed})); then
        1>&2 echo -e "[${script_name} info]" "writing key to ${target_secret_key}"
        ssh-keygen -t "${key_type}" -C "${email}" -N "${passphrase@Q}" -f "${target_secret_key}" -l >${target_secret_art}
        cat "${target_public_key}"
    else
        1>&2 echo -e "[${script_name} error]" "aborted"
    fi
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    main
    exit 0
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
    exit 1
fi
