#!/usr/bin/env bash

. $HOME/opt/lib/ansi.sh
export IFS="
"

tagged_paths_path="$HOME/.config/paths-to-delete.txt"
declare -a known_opts=( "--show-path" )

usage() {
    bar_text_left 231 233 "USAGE: $(ansi_spaced 233 231 "[PATHS... | ${known_opts// / | }]")"
    echo
}
if [ -z "${1}" ]; then
    1>&2 bar_text_left 231 196 "ERROR: missing argument"
    1>&2 usage
    exit 1
fi

declare -a argv=( $@ )
declare -a opts=()
declare -a paths_to_tag=()

for index in ${!argv[@]}; do
    current=$(( $index + 1 ))
    arg="${argv[$index]}"

    case "${arg}" in
        "$(echo -n "${known_opts}" | sed 's/\s\+/|/g')")
            opts+=( "${arg}" )
            ;;
        *)
            if [ -e "${arg}" ]; then
                paths_to_tag+=( "${arg}" )
            else
                1>&2 bar_text_left 231 196 "ERROR: unknown option: $(ansi_spaced 196 231 "${arg}")"
                1>&2 usage
                exit 1
            fi
            ;;
    esac
done

if [ ${#paths_to_tag[@]} -gt 0 ]; then
    tmppath=$(mktemp)
    for path in ${paths_to_tag[@]}; do
        echo -e "\n${path}\n" >> ${tmppath}
    done
    tmpsorted=$(mktemp)
    cat

fi
target_path="$1"
if [ -z "${target_path}" ]; then
    target_path=$HOME/projects
fi

if [ ! -e "${target_path}" ]; then
    1>&2 bar_text_left 231 196 "ERROR: $(ansi_spaced 196 231 "path does not exist $(ansi_underline "${target_path}")")"
    exit 1
fi

find ~/projects -type f -name .todelete -or -type f -name todelete -exec tag-path-for-deletion {} \;

tags_path="$(tag-path-for-deletion --show-path)"

if [ ! -e "${tags_path}" ]; then
    1>&2 bar_text_left 231 196 "ERROR: $(ansi_spaced 196 231 "tags path does not exist $(ansi_underline "${tags_path}")")"
    exit 1
fi
if [ ! -r "${tags_path}" ]; then
    1>&2 bar_text_left 231 196 "ERROR: $(ansi_spaced 196 231 "tags path not readable $(ansi_underline "${tags_path}")")"
    exit 1
fi

declare -a paths_for_deletion=( $(grep "[^[:space:]]" tags_path) )

for path in ${paths_for_deletion[@]}; do
    if [ -e "${path}" ]; then
        bar_text_left  235 220 "DELETING $(ansi_spaced 220 235 "path does not exist $(ansi_spaced 220 235 "${path}")")"
        stderr=$(mktemp)
        stdout=$(mktemp)
        if 2>${stderr} 1>${stdout} rm -rfv "${path}"; then
            ansi_up
            bar_text_left  235 82 "DELETED $(ansi_spaced 82 235 "path does not exist $(ansi_spaced 82 235 "${path}")")"
            sed "/${path//\//\\\/}/d" -i ${tags_path}
        else
            ansi_up
            bar_text_left  216 196 "ERROR DELETING $(ansi_spaced 196 216 "path does not exist $(ansi_spaced 196 216 "${path}")")"
            cat ${stderr}
        fi
    else
        bar_text_left  233 222 "skipping $(ansi_spaced 222 233 "$(ansi_spaced 222 233 "${path}") path does not exist")"
    fi

done

disown -h
