#!/usr/bin/env bash

export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
unset IFS

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -- actual_user="${USER}"
if [ "${USER}" == "root" ]; then
    actual_user="$(/usr/bin/id -un)"
fi

if [ "${actual_user}" != "root" ]; then
    # 1>&2 echo -e "$(basename ${script_name}) must run as root, not ${actual_user}"
    # exit 1
    sudo ${this_script_path}
    exit $?
fi

declare -a command_or_args_regexps=(
    '(audio|coreduet|spotlight|chrome|google|chrome|coreduetd|coreaudiod|logd|biomed|main|/Frameworks/com[.]apple|aned|launchd|agent|continuity|browser|ws.*thread|thermal|monitor|mdns|control|center|airport)'
)
declare -a possibly_duped_pids=()
declare -a possibly_duped_parent_pids=()
declare -A rogue_pids=()
declare -A rogue_parent_pids=()
declare -i pid=-1
declare -i parent_pid=-1
declare -i cmd_and_args=-1

export IFS=$'\n'
declare -a ps_axo_output=()
declare -- stderr=$(mktemp)
declare -a cmdargs_ppid_pid_triple=()
declare -i triple_len=-1
declare -i triple_len=-1

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -- git_repo_path=""
declare -i exit_code=0
declare -- curdir=$(pwd)

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty ${stty_args[@]}
}
usage() {
    repl no echo
    1>&2 echo -e "$(basename $0) <ARGUMENT>"
    repl sane
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message="$@"
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
trace() {
    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
        return 0
    fi

    local -- linenum="${BASH_LINENO[0]}"
    local -- funcname="${FUNCNAME[1]}"
    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
}

process_argv() {
    if ! git_repo_path=$(git rev-parse --show-toplevel); then
        error_prefixed "[${script_name} error]" "${curdir@Q} is not a git repo"
        exit 1
    fi

    repl no echo
    local -i current=0
    local -i index=0
    local -- arg=""

    for index in ${!argv[@]}; do
        current=$(($index + 1))
        arg="${argv[$index]}"
    done

    local -- ps_command="ps axo command,args,ppid,pid"
    if ! ps_axo_output=($(2>${stderr} ps axo command,args,ppid,pid)); then
        warn_prefixed "failed to run ${ps_command}" "$(cat ${stderr})"
        exit 1
    fi

    repl sane
}

main() {
    local -i line_index=0
    local -i current_line_no=0
    for line_index in ${!ps_axo_output[@]}; do
        current_line_no=$(( $line_index + 1 ))
        line=${ps_axo_output[$line_index]}
        for regexp in ${command_or_args_regexps}; do
            rogue_pids=$(ps aux | grep -i -E "${regexp}" | grep -v grep | awk '{ print $2 }')
            for pid in ${rogue_pids}; do
                ps aux | grep -E "^\s*[^[:space:]]+\s+\b${pid}\b"
                kill -9 ${pid} || true
            done
            continue

            if ! cmdargs_ppid_pid_triple=($(gawk "\$1 ~ /${regexp}/{ NFM1=(NF - 1); LNPF=(NFM1-1) for (cmda=1;cmda<=LNPF;cmda++) { suffix=' '; if (cmda == LNPF) {suffix='\n';} printf( '%s%s', \$cmda, suffix); }; printf( '\n%s\n%s\n', \$NFM1, \$NF) }" <<<"${line}")); then
                # 1>&2 echo -e "[warn]" "skipping non-matched line: ${line@Q}"
                continue
            fi
            triple_len=${#cmdargs_ppid_pid_triple[@]}
            if [ ${triple_len} -ne 3 ]; then
                warn_prefixed "[warn]" "cmdargs_ppid_pid_triple should have 2 items but got ${triple_len}: ${cmdargs_ppid_pid_triple[@]@Q}"
                continue
            fi
            cmd_and_args=${cmdargs_ppid_pid_triple[0]}
            parent_pid=${cmdargs_ppid_pid_triple[1]}
            pid=${cmdargs_ppid_pid_triple[2]}
            rogue_parent_pids+=(["${parent_pid}"]="${cmd_and_args}")
            rogue_pids+=(["${pid}"]="${cmd_and_args}")
        done
    done

    echo -e "${rogue_pids[@]@A}"
    echo -e "${rogue_parent_pids[@]@A}"
}

if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
    if process_argv ${argv[@]}; then
        main
    fi
else
    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
fi
repl sane
