#!/usr/bin/env gawk -f

#declare -gr shell_d_macos_var_log_prog_pid_regex='([a-zA-z]+[a-zA-Z0-9]*([[]([0-9]+)[]]))'
#declare -gr shell_d_macos_var_log_bundle_identifier_regex='.*?(com[.]apple[.]([a-zA-Z0-9.]+)).*'
#declare -gr shell_d_macos_var_log_bundle_identifier_and_requestor_regex='^.*?(com[.]apple[.]([a-zA-Z0-9.]+)).*?(requestor\s*=\s*([a-zA-z]+[a-zA-Z0-9]*([[]([0-9]+)[]])?))?$'
BEGIN {
	# IGNORECASE=1
	PROCINFO["sorted_in"] = "@ind_num_asc"
	delete lines
	delete lines_with_sub_matches_by_row
	delete log_lines
	delete system_log_entries
	ln = 0
	ln_wsmbr = 0
	syslog_entry_count = 0
}


function system_log_match_info_get_subexpression_by_name(name)  {

# system_log_match_info[0] = Feb 23 09:30:51 MacBook-Air syslogd[351]: ASL Sender Statistics

# (replace-regexp "^\\(\\s-*[#]\\s-*system_log_match_info[[]\\)\\([1-9][0-9]*\\)\\([]]\\s-*=\\s-*\\(?:.*\\)\\)[\n]\\(\\1\\2[]].*\\)"
#    (match-string (- (/ (length (match-data)) 2) 1)))

# system_log_match_info[1] = Feb 23 09:30:51 MacBook-Air syslogd[351]:
# system_log_match_info[1] = "log_entry_prefix_colon"

# system_log_match_info[2] = Feb 23 09:30:51 MacBook-Air syslogd[351]
# system_log_match_info[2] = "log_entry_prefix"

# system_log_match_info[3] = Feb 23 09:30:51 MacBook-Air
# system_log_match_info[3] = "log_entry_datetime_and_hostname"

# system_log_match_info[4] = Feb 23 09:30:51
# system_log_match_info[4] = "log_entry_datetime_%b %d %H:%M:%S"

# system_log_match_info[5] = Feb 23
# system_log_match_info[5] = "log_entry_datetime_%b %d"

# system_log_match_info[6] = Feb
# system_log_match_info[6] = "log_entry_datetime_%b"

# system_log_match_info[7] = 23
# system_log_match_info[7] = "log_entry_datetime_%d"

# system_log_match_info[8] = 09:30:51
# system_log_match_info[8] = "log_entry_datetime_%H:%M:%S"

# system_log_match_info[9] = 09
# system_log_match_info[9] = "log_entry_datetime_%H"

# system_log_match_info[10] = 30
# system_log_match_info[10] = "log_entry_datetime_%M"

# system_log_match_info[11] = 51
# system_log_match_info[11] = "log_entry_datetime_%S"

# system_log_match_info[12] = MacBook-Air
# system_log_match_info[12] = "log_entry_hostname"

# system_log_match_info[13] = syslogd[351]
# system_log_match_info[13] = "log_entry_process_and_pid"

# system_log_match_info[14] = syslogd
# system_log_match_info[14] = "log_entry_process_name"

# system_log_match_info[15] = 351
# system_log_match_info[15] = "log_entry_process_pid"

# system_log_match_info[16] = ASL Sender Statistics
# system_log_match_info[16] = log_entry_message

}
function is_system_log_entry_first_line(line)
{
	delete system_log_match_info
	if (pos = match(line, /^(((((([A-Z][a-z]{2})\s+([0-9]+))\s+(([0-9]{2})[:]([0-9]{2})[:]([0-9]{2})))\s+([^[:space:]]+))\s+(([a-zA-Z]+[a-zA-Z0-9]*)[[]([0-9]+)[]])):)\s*(.*)$/, system_log_match_info)) {
		system_log_entries[syslog_entry_count] = line
		prefix = ""
		for (idx = 0; idx < (length(system_log_match_info) / 3); idx++) {
                    # prefix=system_log_match_info[idx]
                    printf("system_log_match_info[%d] = %s\n", idx, system_log_match_info[idx]) > "/dev/stderr";
                    # prefix = sprintf("%s%s%s", prefix, system_log_match_info[idx], FS)
		}
                print("") > "/dev/stderr"
		printf("is_system_log_entry_first_line %s => prefix: '%s'\n", NR, prefix);
                print("") > "/dev/stderr"
		# system_log_entry_prefixes[syslog_entry_count]=system_log_match_info[]
		return 1
	}
	return 0
}

{
	line = $0
	lines[ln] = line
	delete match_info
	if (is_system_log_entry_first_line(line)) {
	} else {
		#
		# aWYocG9zID0gbWF0Y2goJDAsIC9eXHMqKC4qPyhjb21bLl1hcHBsZVsuXShbYS16QS1aMC05Ll0rKSkuKj8oKHJlcXVlc3RvclxzKj1ccyopPygoW2EtekEtel0rW2EtekEtWjAtOV0qKShbW10oWzAtOV0rKVtdXSk/KSk/Lio/KStccyo/JC8sIG1hdGNoX2luZm8pKSB7
		#
		# Feb 23 00:07:34 MacBook-Air syslogd[351]: ASL Sender Statistics
		# if (line ~ /^([A-Z][a-z]{2})\s+([0-9]+)\s+(([0-9]{2})[:]([0-9]{2})[:]([0-9]{2}))\s+([^[:space:]]+)\s+([a-zA-Z]+[a-zA-Z0-9]*)[[]([0-9]+)[]]:\s*(.*)$/ )
		if (pos = match($0, /(((name\s*=\s*)?(([a-zA-Z]+[.]([a-zA-Z0-9]+[.]?)+)))(\s*,\s*|.*?)?((requestor\s*=\s*)?(([a-zA-Z]+[a-zA-Z0-9]*)([[]([0-9]+)[]])))?|"(.*?)([a-zA-Z]+[.]([a-zA-Z0-9]+[.]?)+)"(.*?))/, match_info)) {
			subexpr = 0
			printf "<line:%d match_info_length=%d>\n", ln, length(match_info)
			for (key in match_info) {
				printf "\t\033[1;38;5;222m%s\033[0m=%s\n", key, match_info[key]
			}
			# lines_with_sub_matches_by_row[ln_wsmbr]["NR"]=NR;
			# lines_with_sub_matches_by_row[ln_wsmbr]["NF"]=NF;
			while (match_info[subexpr]) {
				submatch = match_info[subexpr]
				x
				printf "\033[1;38;5;220msubexpr[%d]\033[0m=%s\n", subexpr, submatch
				# printf("lines_with_\x1b[1;38;5;220msub_matches\x1b[0m_by_row[%s][\x1b[1;38;5;220m%s\x1b[0m]=%s\n", ln_wsmbr, subexpr, submatch);
				lines_with_sub_matches_by_row[ln_wsmbr][subexpr] = submatch
				subexpr++
			}
			printf "</line:%d>\n", ln
			print ("")
			# lines_with_sub_matches_by_row[ln_wsmbr]["NR"]=NR;
			# lines_with_sub_matches_by_row[ln_wsmbr]["NF"]=NF;
			ln_wsmbr++
		}
	}
	ln++
}
