#!/usr/bin/env bash

script_path="$(2>/dev/null 1>/dev/null cd $(dirname ${BASH_SOURCE[0]}) && pwd)"

if [ -x "${script_path}/webarchive" ]; then
    ${script_path}/webarchive $@ &
    disown -h
else
    2>&1 echo "not executable: ${script_path}/webarchive"
fi
