#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -- this_script_path="${script_path}/${script_name}"
declare -- usefulness="does stuff"

declare -a description_lines=(
    "these lines are supposed to describe the usefulness of ${script_name}"
    "beyond \"${usefulness}\" such that the output of ${script_name}\x27"
    "help looks not unlike a nice unix manpage"
)

declare -a argv=(${@})
declare -i argc=${#argv[@]}
declare -a stdin_lines=(${@})
declare -i stdin_line_count=${#stdin_lines[@]}
declare -- git_repo_path=""
declare -i code=0
declare -i argv_return_code=0
declare -i stdin_return_code=0

declare -- curdir="$PWD"
if [ -z "${PWD}" ]; then
    curdir=$(pwd)
fi

# 0=`declare -- debug_prefix_color_rgb="138;226;52"`
# 1=`debug`
# 2=`_prefix`
# 3=`prefix`
# 4=`_color`
# 5=`color`
# 6=`_rgb`
# 7=`"138;226;52"`
# 8=`138;226;52`
# 9=`138`
# 10=`226`
# 11=`52`

# ^declare\s-+[-][-]\s-+\([a-z]+\)\([_]\(prefix\)\)?\([_]\(color\)\)\([_]rgb\)=\("\(\([0-9]\{1,3\}\);\([0-9]\{1,3\}\);\([0-9]\{1,3\}\)[m;]?\)"\)\s-*$ → declare -- \1\2_fg_\5\6="\\x1b[1;38;2;\,(match-string 9);\,(match-string 10);\,(match-string 11)m"[\n]declare -- \1\2_bg_\5\6="\\x1b[1;48;2;\,(match-string 9);\,(match-string 10);\,(match-string 11)m"

declare -- error_prefix_color_rgb="239;41;41"
declare -- error_color_rgb="204;0;0"

declare -- achtung_prefix_color_rgb="245;121;0"
declare -- achtung_color_rgb="206;92;0"

declare -- warn_prefix_color_rgb="252;233;79"
declare -- warn_color_rgb="237;212;00"

declare -- info_prefix_color_rgb="52;101;164"
declare -- info_color_rgb="114;159;207;"

declare -- msg_prefix_color_rgb="186;189;182"
declare -- msg_color_rgb="136;138;133"

declare -- display_prefix_color_rgb="238;238;236"
declare -- display_color_rgb="211;215;207"

declare -- debug_prefix_color_rgb="138;226;52"
declare -- debug_color_rgb="115;210;22"

on_exit() {
    2>/dev/random 1>/dev/random stty sane
}
on_ctrlc() {
    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
    exit 1
}
trap on_exit exit
trap on_ctrlc hup
trap on_ctrlc int
trap on_ctrlc bus
trap on_ctrlc segv
trap on_ctrlc sys

repl() {
    local -a stty_args=()
    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
    2>/dev/random 1>/dev/random stty "${stty_args[@]}"
}
exit_error() {
    error "${@}"
    exit 1
}

achtung_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
}
achtung() {
    local -- linenum="${BASH_LINENO[0]}"
    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
}
warn_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
}
warn() {
    local -- linenum="${BASH_LINENO[0]}"
    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
}
error() {
    local -- linenum="${BASH_LINENO[0]}"
    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
}
error_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
}
info() {
    local -- linenum="${BASH_LINENO[0]}"
    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
}
info_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
}
msg() {
    local -- linenum="${BASH_LINENO[0]}"
    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
}
msg_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
}
display() {
    local -- linenum="${BASH_LINENO[0]}"
    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
}
display_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
}
debug_prefixed() {
    local -- prefix="$1"
    shift
    local -- message=${@}
    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
}
debug() {
    local -- linenum="${BASH_LINENO[0]}"
    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
}
declare -a all_which_match=()
declare -A which_modified_ts_to_path_map=()
declare -A which_created_ts_to_path_map=()
declare -A which_name_to_path_map=()
declare -- pos=""
declare -- bin=''
declare -- bin_path=''
declare -- bin_name=''
declare -- exec_name=''
declare -- each_cellar_exec_name=''
declare -a exec_path_list=()
declare -a find_cellar_bin_path_list=()
declare -- name=''
declare -- stderr=$(mktemp)
declare -i code=0
declare -- brew_cellar_path=""
declare -a found_which_a=()
declare -a found_cellar_bins=()

if [ ${argc} -eq 0 ]; then
    error_prefixed "${script_name}" "missing arguments: <EXECUTABLE_NAME>"
    exit 1
fi


for index in ${!argv[@]}; do
    code=0
    current=$(($index + 1))
    arg="${argv[$index]}"
    pos="$(printf '%*s of %s' ${#argc} ${current} ${argc})"

    brew_cellar_path=""
    found_which_a=()
    found_cellar_bins=()

    if [[ "${arg}" =~ / ]]; then
        if [ -x "${arg}" ]; then
            exec_path_list+=("${arg}")
        fi
        exec_name="$(basename "${arg}")"
    else
        exec_name="${arg}"
    fi

    if ! found_which_a=($(2>${stderr} which -a "${exec_name}")); then
        code=$?
    fi

    if [ ${code} -ne 0 ]; then
        if [ -s "${stderr}" ]; then
            error_prefixed "${script_name} ${pos} error" "command \x60which -a ${exec_name@Q}\x27 failed with code ${code}"
            error_prefixed "${script_name} ${pos} error" "$(cat "${stderr}")"
        else
            error_prefixed "${script_name} ${pos} error" "command \x60which -a ${exec_name@Q}\x27 failed with code ${code}"
        fi
        exit ${code}
    elif [ ${#found_which_a[@]} -eq 0 ]; then
        error_prefixed "${script_name} ${pos} error" "cannot find executable named ${name@Q}"
        exit 1
    fi

    exec_path_list+=(${found_which_a[@]})
    if ! brew_cellar_path="$(2>${stderr} brew --cellar "${exec_name}")";then
        code=$?
    fi

    if [ ${code} -ne 0 ]; then
        if [ -s "${stderr}" ]; then
            error_prefixed "${script_name} ${pos} error" "command \x60brew --cellar ${exec_name@Q}\x27 failed with code ${code}"
            error_prefixed "${script_name} ${pos} error" "$(cat "${stderr}")"
        else
            error_prefixed "${script_name} ${pos} error" "command \x60brew --cellar ${exec_name@Q}\x27 failed with code ${code}"
        fi
        exit ${code}
    elif [ ${#found_which_a[@]} -eq 0 ]; then
        error_prefixed "${script_name} ${pos} error" "cannot get ${name@Q}"
        exit 1
    fi
    # found_cellar_bins=( $(find "${brew_cellar_path}" -mindepth 1 -maxdepth 1 -type d -exec path canon "{}/bin/${exec_name}" \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort -nur))

    found_cellar_bins=( $(find "${brew_cellar_path}" -mindepth 1 -maxdepth 1 -type d -exec path canon "{}/bin/${exec_name}" \; ) )
    for bin_path in ${found_cellar_bins[@]}; do
        error_prefixed "${script_name} ${pos} error" "command \x60brew --cellar ${exec_name@Q}\x27 failed with code ${code}"

    done

done
exit 1

# 1>&2 echo -e "\x1b[1;38;2;252;233;79m[\x1b[1;38;2;245;121;0m${script_name} \x1b[1;38;2;211;215;207m${pos}\x1b[1;38;2;252;233;79m]\x1b[0m" "\x1b\0m\x1b[1;38;2;252;233;79m${arg}\x1b[0m"
### #
### #
### #
### #
### #
### #
### # which -a jq | unique-lines | xargs -Ieachwhich path canon 'eachwhich';
### # find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort -nur
### #
### #
### #
### #
### #
### #
### # which  -a bash
### # which jq
### # which -a jq
### # which -a
### # which -a jq | unique-lines
### # which -a jq | unique-lines; path canon /opt/homebrew/bin/jq
### # which -a jq | unique-lines; brew --cellar jq
### # which -a jq | unique-lines; /bin/ls $(brew --cellar jq)
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path join '{}' 'bin' \;
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path join '{}' 'bin' \; | tail -1 | xargs ls
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path join '{}' 'bin' \; | tail -1 | xargs ls -latrh
### # which -a which
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path join '{}' 'bin/jq' \;
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \;
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; | sort
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; | sort -ru
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; | sort -r
### # which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; | sort -u
### # (which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | sort
### # (which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | sort  | xargs -Ieachwhich gstat -c '%Y %W eachwhich' 'eachwhich'
### # (which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | sort  | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'
### # (which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort
### # (which -a jq | unique-lines; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort -nr
### # (which -a jq | unique-lines | xargs -Ieachwhich path canon 'eachwhich'; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort -nr
### # (which -a jq | unique-lines | xargs -Ieachwhich path canon 'eachwhich'; find $(brew --cellar jq) -mindepth 1 -maxdepth 1 -type d -exec path canon '{}/bin/jq' \; ) | xargs -Ieachwhich gstat -c '%Y %W %F eachwhich' 'eachwhich'  | sort -nur
