#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
export IFS=$'\n'

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

declare -a argv=(${@})
declare -i argc=${#argv[@]}

# export IFS=$'\x7c' # pipe
declare -- jq_pipeline=""


jq_pipeline_from_argv() {
    if [ ${argc} -gt 0 ]; then
        printf '%s | ' "${argv[@]}" | sed -E 's/\s*[|]\s*$//g'
    else
        printf '.'
    fi
}


wezterm cli list --format="json" </dev/stdin | jaq -r ".[] | {pane_id,tty_name,title,path: .cwd | match(\"^[a-zA-Z0-9-]+://((?<path>[a-zA-Z0-9_/.,[:space:]-]+[^/]+)([/]?))\$\") | .captures[1].string,tab_id,window_id,window_title,tab_title,cursor_shape,cursor_visibility,cursor_x,cursor_y,cwd,is_active,is_zoomed,left_col,size,top_row,workspace}" | jaq -s | jaq 'unique_by(.pane_id)' | jaq -r "${jq_pipeline:-$(jq_pipeline_from_argv)}"
