#!/Users/gabrielfalcao/.shell.d/.venv/bin/python3

# wz-parse-get-text-output: parses each effective bash history line from
# output of ``wezterm cli get-text``, either from command-line or from
# subprocess call. For the latter case, Accepts pane-id option to pass
# to ``wezterm cli get-text --pane-id=<pane-id>``
#
# supports outputting parse result to stdout and/or writing to file

import sys
import click
import re
import os
import json
import subprocess

from collections.abc import Iterator, Iterable
from typing import Self, Any, T, TypeVar, List, Tuple, Union
from pprint import pprint, pformat
from pathlib import Path

@click.command()
@click.option("-p", "--pane-id", type=int, help="optional frame id used when stdin is a tty or --subprocess is present", callback=validate_option__pane_id)
def main(pane_id):
    """
    parses output from the command ``wezterm cli get-text ``
    """





if __name__ == '__main__':
    main()
