#!/usr/bin/env bash

set -umeTE
set +f
set -o pipefail
unset IFS
declare -i code=-1

declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
declare -- this_script_path="${script_path}/${script_name}"

export IFS=$'\n'

declare -a argv=($@)
declare -i argc=${#argv[@]}
declare -i index=0
declare -i current=0
declare -- arg=""
declare -- pos=""

declare -r prog=$(which yt-dlp)
# --merge-output-format
declare -a yt_dlp_args_main=(
    # '-t'
    # 'mkv'
    '--retries'
    '37'
    '--continue'
    '--mtime'
    '--write-info-json'
    '--write-subs'
    '--write-auto-subs'
    '--write-playlist-metafiles'
    '--write-thumbnail'
    '--progress'
    '-o' "./%(webpage_url_domain)s/%(media_type)s_%(uploader_id)s_%(channel_id)s_%(id)s_%(title)s.%(acodec)s.%(vcodec)s.%(ext)s"
    '--sub-format'
    'srt'

    # '--js-runtimes'
    # 'deno:${HOME}/.deno/bin/deno'

    # '--js-runtimes'
    # 'node:${HOME}/.nvm/versions/node/v25.8.1/bin/node'

    # '--js-runtimes'
    # 'bun:${HOME}/.bun/bin/bun'

    '--cookies'
    "${HOME}/.config/yt-dlp.youtube.cookies.txt"

    # '--write-pages'
    # '--console-title'
    '--print-traffic'
    ${argv[@]}
)

1>&2 echo "${prog} ${yt_dlp_args_main[@]}"
${prog} ${yt_dlp_args_main[@]}
