#!/usr/bin/env bash

export IFS=$'\n'
set -umeTE
set +f
set -o pipefail
unset IFS

script_name="$(basename "${BASH_SOURCE[0]}")"
script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
this_script_path="${script_path}/${script_name}"

declare -a argv=($@)
declare -i argc=${#argv[@]}

script_name="$(basename "${BASH_SOURCE[0]}")"

declare -- cache_path="$(pwd)/yt-dlp.cache"
mkdir -p "${cache_path}"

# --merge-output-format
declare -a yt_dlp_args=(
    '-t'
    'mkv'
    '--retries'
    '37'
    '--continue'
    '--mtime'
    '--write-info-json'
    '--write-subs'
    '--write-auto-subs'
    '--write-playlist-metafiles'
    '--write-thumbnail'
    '--progress'
    '-o' "$(pwd)/%(webpage_url_domain)s/%(channel)s/%(media_type)s.%(id)s/%(title)s%(ext)s"
    # '--console-title'
    # '--write-pages'
    # '--sub-format'
    # 'srt'
    '--js-runtimes'
    'node:"${HOME}/.nvm/versions/node/v22.18.0/bin/node"'

    # '--recode-video'
    # 'mkv'

    '--force-keyframes-at-cuts'

    # '-o'
    # '"test'
    # 'video.%(ext)s"'

    # '--embed-subs'
    # '--embed-thumbnail'
    # '--embed-chapters'
    # '--embed-info-json'

    '--cache-dir'
    '"${cache_path}"'
    ${argv[@]}

)
$HOME/.shell.d/.venv/bin/yt-dlp ${yt_dlp_args[@]}
