[alias]
c = "check"


d = "dist"
j = "check --offline --message-format=json-diagnostic-short"
tj = "test --offline --message-format=json-diagnostic-short"
cjq = "check --offline --message-format=json"
tjq = "test --offline --message-format=json"
q = "quickcheck"
ip = "install-local --all-features"
ipo = "install --all-features --offline --path ."
n = "nextest run -j1 --ff"
# t = "test --offline --color always -- --nocapture --color always"
r = "run --offline"
t = "test --offline -j 1 --color always --all-features -- --nocapture --color always --test-threads 1"  # -- -Z --ensure-time
test-all-features = "test --offline -j 1 --all-features --color always -- --nocapture --color always"
f = "fix --all-targets --allow-staged --allow-dirty"
fb = "fix --all-targets --allow-staged --allow-dirty --broken-code"
cfb = "fix --allow-staged --allow-dirty --broken-code"
docs = "doc -Zunstable-options -Zrustdoc-scrape-examples"
[craft]


[dep.paths]
iocore = "~/projects/work/poems.codes/tools/iocore"
sanitation = "~/projects/work/poems.codes/tools/sanitation"


# [build]
# rustflags = "-C opt-level=0 -g"


[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size. https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level
lto = true
panic = "abort"
codegen-units = 1
# https://github.com/johnthagen/min-sized-rust?tab=readme-ov-file#remove-fmtdebug


[profile.dev]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.


[target.mips-unknown-linux-musl]
linker = "/opt/homebrew/Cellar/mipsel-linux-gnu-binutils/2.46.0/bin/mipsel-linux-gnu-ld"


# "/opt/homebrew/Cellar/mipsel-linux-gnu-binutils/2.46.0/mipsel-linux-gnu/bin"
# "/opt/homebrew/Cellar/mipsel-linux-gnu-binutils/2.46.0/bin"


[target.aarch64-elf-binutils]
linker = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-ld
# addr2line = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-addr2line
# ld.bfd = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-ld.bfd
# objcopy = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-objcopy
# gprof = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-gprof
# strip = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-strip
# elfedit = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-elfedit
# readelf = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-readelf
# ranlib = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-ranlib
# as = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-as
# nm = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-nm
# objdump = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-objdump
# c++filt = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-c++filt
# ar = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-ar
# strings = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-strings
# size = /opt/homebrew/opt/aarch64-elf-binutils/bin/aarch64-elf-size


[target.arm-linux-gnueabihf-binutils]
linker = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-ld
# objcopy = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-objcopy
# addr2line = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-addr2line
# size = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-size
# ld.bfd = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-ld.bfd
# readelf = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-readelf
# as = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-as
# gprof = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-gprof
# nm = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-nm
# elfedit = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-elfedit
# ar = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-ar
# strip = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-strip
# ranlib = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-ranlib
# strings = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-strings
# objdump = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-objdump
# c++filt = /opt/homebrew/opt/arm-linux-gnueabihf-binutils/bin/arm-linux-gnueabihf-c++filt


[target.arm-none-eabi-binutils]
linker = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld
# ld.bfd = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld.bfd
# objcopy = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-objcopy
# strings = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-strings
# c++filt = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-c++filt
# objdump = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-objdump
# ar = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ar
# nm = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-nm
# gprof = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-gprof
# as = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-as
# addr2line = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-addr2line
# strip = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-strip
# ranlib = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ranlib
# size = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-size
# readelf = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-readelf
# elfedit = /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-elfedit


[target.cargo-binutils]
linker = /opt/homebrew/opt/cargo-binutils/bin/rust-ld
# ar = /opt/homebrew/opt/cargo-binutils/bin/rust-ar
# nm = /opt/homebrew/opt/cargo-binutils/bin/rust-nm
# as = /opt/homebrew/opt/cargo-binutils/bin/rust-as
# objdump = /opt/homebrew/opt/cargo-binutils/bin/cargo-objdump
# cov = /opt/homebrew/opt/cargo-binutils/bin/rust-cov
# objdump = /opt/homebrew/opt/cargo-binutils/bin/rust-objdump
# profdata = /opt/homebrew/opt/cargo-binutils/bin/cargo-profdata
# strip = /opt/homebrew/opt/cargo-binutils/bin/cargo-strip
# objcopy = /opt/homebrew/opt/cargo-binutils/bin/rust-objcopy
# nm = /opt/homebrew/opt/cargo-binutils/bin/cargo-nm
# readobj = /opt/homebrew/opt/cargo-binutils/bin/cargo-readobj
# profdata = /opt/homebrew/opt/cargo-binutils/bin/rust-profdata
# strip = /opt/homebrew/opt/cargo-binutils/bin/rust-strip
# size = /opt/homebrew/opt/cargo-binutils/bin/cargo-size
# cov = /opt/homebrew/opt/cargo-binutils/bin/cargo-cov
# readobj = /opt/homebrew/opt/cargo-binutils/bin/rust-readobj
# lld = /opt/homebrew/opt/cargo-binutils/bin/rust-lld
# size = /opt/homebrew/opt/cargo-binutils/bin/rust-size
# objcopy = /opt/homebrew/opt/cargo-binutils/bin/cargo-objcopy


[target.i686-elf-binutils]
linker = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-ld
# c++filt = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-c++filt
# objdump = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-objdump
# ld.bfd = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-ld.bfd
# strings = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-strings
# readelf = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-readelf
# size = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-size
# elfedit = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-elfedit
# ranlib = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-ranlib
# addr2line = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-addr2line
# nm = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-nm
# ar = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-ar
# gprof = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-gprof
# strip = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-strip
# as = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-as
# objcopy = /opt/homebrew/opt/i686-elf-binutils/bin/i686-elf-objcopy


[target.m68k-elf-binutils]
linker = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-ld
# readelf = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-readelf
# elfedit = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-elfedit
# gprof = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-gprof
# strings = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-strings
# strip = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-strip
# size = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-size
# c++filt = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-c++filt
# objdump = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-objdump
# ranlib = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-ranlib
# addr2line = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-addr2line
# objcopy = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-objcopy
# ld.bfd = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-ld.bfd
# as = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-as
# nm = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-nm
# ar = /opt/homebrew/opt/m68k-elf-binutils/bin/m68k-elf-ar


[target.mipsel-linux-gnu-binutils]
linker = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-ld
# readelf = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-readelf
# ar = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-ar
# strip = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-strip
# nm = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-nm
# as = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-as
# gprof = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-gprof
# elfedit = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-elfedit
# addr2line = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-addr2line
# c++filt = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-c++filt
# objdump = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-objdump
# ranlib = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-ranlib
# strings = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-strings
# objcopy = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-objcopy
# ld.bfd = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-ld.bfd
# size = /opt/homebrew/opt/mipsel-linux-gnu-binutils/bin/mipsel-linux-gnu-size


[target.riscv64-elf-binutils]
linker = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ld
# strings = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-strings
# c++filt = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-c++filt
# objdump = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-objdump
# gprof = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-gprof
# strip = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-strip
# elfedit = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-elfedit
# readelf = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-readelf
# ranlib = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ranlib
# size = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-size
# nm = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-nm
# ar = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ar
# as = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-as
# objcopy = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-objcopy
# ld.bfd = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ld.bfd
# addr2line = /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-addr2line


[target.x86_64-elf-binutils]
linker = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-ld
# ld.bfd = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-ld.bfd
# objcopy = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-objcopy
# nm = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-nm
# strip = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-strip
# ar = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-ar
# addr2line = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-addr2line
# gprof = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-gprof
# as = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-as
# strings = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-strings
# c++filt = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-c++filt
# objdump = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-objdump
# ranlib = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-ranlib
# readelf = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-readelf
# size = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-size
# elfedit = /opt/homebrew/opt/x86_64-elf-binutils/bin/x86_64-elf-elfedit


[target.x86_64-linux-gnu-binutils]
linker = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-ld
# addr2line = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-addr2line
# ar = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-ar
# as = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-as
# c++filt = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-c++filt
# elfedit = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-elfedit
# gprof = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-gprof
# ld.bfd = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-ld.bfd
# nm = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-nm
# objcopy = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-objcopy
# objdump = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-objdump
# ranlib = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-ranlib
# readelf = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-readelf
# size = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-size
# strings = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-strings
# strip = /opt/homebrew/opt/x86_64-linux-gnu-binutils/bin/x86_64-linux-gnu-strip


# [target.binutils]
# /opt/homebrew/opt/binutils/bin/windres
# /opt/homebrew/opt/binutils/bin/strings
# /opt/homebrew/opt/binutils/bin/objdump
# /opt/homebrew/opt/binutils/bin/c++filt
# /opt/homebrew/opt/binutils/bin/strip
# /opt/homebrew/opt/binutils/bin/srconv
# /opt/homebrew/opt/binutils/bin/windmc
# /opt/homebrew/opt/binutils/bin/readelf
# /opt/homebrew/opt/binutils/bin/sysdump
# /opt/homebrew/opt/binutils/bin/elfedit
# /opt/homebrew/opt/binutils/bin/dlltool
# /opt/homebrew/opt/binutils/bin/addr2line
# /opt/homebrew/opt/binutils/bin/nm
# /opt/homebrew/opt/binutils/bin/ar
# /opt/homebrew/opt/binutils/bin/coffdump
# /opt/homebrew/opt/binutils/bin/objcopy
# /opt/homebrew/opt/binutils/bin/size
# /opt/homebrew/opt/binutils/bin/ranlib
# /opt/homebrew/opt/binutils/bin/dllwrap
